{
  "hash": "a5983c92a5dbeecf4d83bab3510c835d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Why target-mediated drug disposition is rarely visible in T-cell engager pharmacokinetics\"\nsubtitle: \"Working specification\"\ndescription: \"T-cell engagers are dosed far below the amount needed to saturate CD3, so a sharp concentration drop should be the usual sight and is not. This works through four explanations, tests each against published population pharmacokinetic models, and says which one carries the weight.\"\ncategories: [pharmacometrics, pharmacokinetics, oncology, working document]\ndate: last-modified\nexecute:\n  freeze: auto\n  warning: false\n  message: false\ntoc: true\ntoc-depth: 3\ntoc-location: left\ntoc-expand: true\nhtml-math-method: mathjax\n---\n\n::: {.callout-important appearance=\"simple\"}\n**Two sources have been read in full, and none of the transcribed parameter\nvalues has been checked against a printed table.** The odronextamab,\nmosunetuzumab, teclistamab and elranatamab parameters driving every figure and\ncalculation below were taken from an open-access full text and from\n`nlmixr2lib` model files, not from the published tables. Sections 3 and 7 compute their conclusions\nfrom those numbers, so both conclusions inherit whatever is wrong in them.\nSection 5 rests on two drugs, which is where its own limits section says\nit rests.\n[References](references.qmd) carries a status marker on every source and\n[the project index](index.qmd) lists the other documents in this folder.\n:::\n\n## In brief\n\n**The observation.** A T-cell engager (TCE) binds CD3 on T cells with\nnanomolar affinity, and CD3 internalizes with a half-life near an hour.\nA first dose of 0.16 mg of epcoritamab or 0.7 mg of odronextamab is the\nsame order of magnitude as the CD3 receptors circulating in blood, and a\nsmall fraction of what those receptors internalize in a week.\nEvery ingredient of textbook target-mediated drug disposition (TMDD) is\npresent, so the concentration-time profile after a priming dose should\nfall off a cliff. Published profiles do not. The approved hematology\nTCEs report terminal half-lives of 6 to 22 days, which is antibody-like.\n\n**The answer this document argues for, in one line.** TMDD is there and is\nlarge, it is reported as *time-dependent clearance* rather than as a\nconcentration nonlinearity, and the priming doses that could show the\nnonlinearity sit below the Michaelis constant, where a Michaelis-Menten\nelimination is arithmetically indistinguishable from a first-order one.\n\n**The decisive number.** For odronextamab the fitted Michaelis constant is\n$k_m$ = 1.95 mg/L and the 0.7 mg priming dose reaches a peak concentration\nof 0.14 mg/L. The entire priming-dose profile lives at $C/k_m \\le 0.07$.\nSection 3 simulates that profile with target depletion switched off and\nfinds total clearance varying from 7.2 to 7.7 L/day across a 900-fold\nconcentration range. The mechanism is saturable and behaves linearly,\nbecause the dose is too small to saturate it.\n\n**What happens to the target sink, corrected.** The decaying clearance term\nin the published models is 26-fold for odronextamab and only 1.6 to 2.2-fold\nfor teclistamab, mosunetuzumab and talquetamab, so on its own it cannot\naccount for the class. Two things are being conflated. Odronextamab's decay\nhas a half-life of 0.64 days, which is target-cell killing. The others decay\nover 16 to 24 days, which is too slow to be a receptor pool emptying and is\nwhat their own authors attribute to falling tumor burden. Section 4 separates\nthem, and Section 4a measures the target-mediated clearance the way it should\nbe measured: against what the same molecule would clear at with no target.\nTeclistamab clears 5.3 times faster than a target-free antibody at treatment\nstart, and only a 2.2-fold part of that ever decays, because CD3 is not\ndepletable.\n\n**Hypothesis 3, flip-flop kinetics.** True for teclistamab early in\ntreatment, false for elranatamab, and inapplicable to the intravenous\ndrugs. Teclistamab's absorption half-life is 5.2 days against an effective\nelimination half-life of 3.8 days at treatment start, so absorption is\nrate-limiting then, and 8.4 days at steady state, so it is not\nrate-limiting later. Elranatamab absorbs with a 4.7-day half-life and\neliminates with a 25-day one, so absorption is never rate-limiting for it.\nSection 5 works both.\n\n**Out of scope, stated once.**\n\n- ❌ **A new TMDD model.** Nothing here is fit. Every parameter is\n  transcribed from a published model and simulated forward.\n- ❌ **Quantitative systems pharmacology.** No trimer formation, no\n  cytokine cascade, no tumor dynamics. The CD3-plus-antigen binding model\n  of Pearce et al. is the deepest mechanism used.\n- ❌ **Dose selection.** No regimen, step-up schedule or starting dose\n  should be taken from this document.\n- ✅ **The parameter survey.** Compiling fixed and random effects across\n  the published TCE models is a deliverable in its own right, and it lives\n  in [PK parameters](pk-parameters.qmd) rather than here.\n\n## 1. The Observation, as Numbers\n\nPearce et al. tabulate published half-lives for 29 TCEs in cynomolgus\nmonkey and in patients. The approved hematology molecules cluster near a\nweek, and the solid-tumor and non-Fc molecules do not.\n\n| T-cell engager | Target | Format and route | Human half-life (days) |\n|:---|:---|:---|---:|\n| Elranatamab | BCMA | IgG, subcutaneous | 22 |\n| Talquetamab | GPRC5D | IgG, subcutaneous | 8–12 |\n| Mosunetuzumab | CD20 | IgG, intravenous | 6–11 |\n| Glofitamab | CD20 | IgG 2:1, intravenous | 6–11 |\n| Tarlatamab | DLL3 | half-life extended, intravenous | 5.7 |\n| Teclistamab | BCMA | IgG, subcutaneous | 3.8 |\n| HPN217 | BCMA | albumin-binding, intravenous | 2.8 |\n| CB307 | PSMA | albumin-binding, intravenous | 3 |\n| PF-06671008 | CDH3 | bispecific, intravenous | 1.2 |\n| Tebentafusp | gp100 | ImmTAC, intravenous | 0.3 |\n| Blinatumomab | CD19 | BiTE, continuous infusion | 0.09 |\n\n: Published human half-lives. Every row except blinatumomab is from Table 1\nof Pearce et al.; blinatumomab is the 2.11 hours in its label. ⚠️ Transcribed,\nunverified. {tbl-colwidths=\"[24,12,34,30]\"}\n\nTwo things separate the top of the table from the bottom, and neither is\ntarget engagement. The long half-lives belong to molecules with an intact\nFc domain and therefore neonatal Fc receptor recycling, and the short ones\nbelong to formats without it. Blinatumomab at 54 kDa is below the renal\nfiltration threshold and is cleared in hours regardless of what it binds.\nSo the question is narrower than it first appears: **why does an\nFc-containing TCE, dosed at a fraction of its target pool, show the\nhalf-life of an ordinary IgG?**\n\n## 2. Four Explanations, and How Each Would Be Falsified\n\n| # | Explanation | Would be falsified by |\n|:--|:---|:---|\n| 1 | The dose sits below the Michaelis constant, where saturable elimination is linear | A published $k_m$ comparable to, or below, the priming-dose peak concentration |\n| 2 | The target sink is destroyed within the first cycle, so the nonlinearity has no time to show | A published model with a time-invariant nonlinear clearance and no decay term |\n| 3 | Slow subcutaneous absorption rate-limits the terminal slope | An absorption rate constant fast relative to elimination, or the same flat profile intravenously |\n| 4 | Sampling and assay quantitation limits hide the drop | Dense early sampling at a priming dose showing a log-linear decline |\n\n: The four explanations and their falsifiers {tbl-colwidths=\"[5,55,40]\"}\n\nExplanations 1 and 2 both survive Sections 3 and 4. Explanation 3 survives\nin one narrow case and is examined in Section 5. Explanation 4 is\nuntestable with what is public and is set out in Section 6 as a data\nrequest rather than a finding.\n\n## 3. Explanation 1: The Priming Dose Sits Below the Michaelis Constant\n\nOdronextamab is the test case, because Kovalenko et al. published a model\nwith an explicit Michaelis-Menten elimination and reported $k_m$.\n\nThe structural model is a two-compartment disposition with parallel\nfirst-order and Michaelis-Menten elimination, and the maximum velocity\ndeclines with time since first dose:\n\n$$\n\\frac{dV_{\\max}}{dt} = -K_v\\left(V_{\\max} - V_{\\max,\\rm asym}\\right),\n\\qquad\nCL_{MM} = \\frac{V_{\\max}}{k_m + C}\\,V_c\n$$\n\nwith $V_{\\max,0}$ = 2.93 mg/L/day, $k_m$ = 1.95 mg/L, $K_v$ = 1.09 /day,\n$V_{\\max,\\rm asym}/V_{\\max,0}$ = 0.262, linear $CL$ = 0.189 L/day,\n$V_c$ = 4.99 L, $V_p$ = 4.42 L and $Q$ = 1.21 L/day.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsuppressMessages({\n  library(rxode2); library(dplyr); library(tidyr)\n  library(ggplot2); library(patchwork); library(xgxr)\n})\nxgx_theme_set()\nknitr::opts_chunk$set(fig.width = 7, fig.height = 5)\n\nodro <- rxode2({\n  vmax  <- vmax_asym + (vmax0 - vmax_asym) * exp(-kv * time)\n  cc    <- central / vc\n  kmm   <- vmax / (km + cc)\n  cltot <- cl + kmm * vc\n  d/dt(central)    <- -kmm*central - cl/vc*central - q/vc*central + q/vp*peripheral\n  d/dt(peripheral) <-  q/vc*central - q/vp*peripheral\n})\n\npar_odro <- c(cl = 0.189, q = 1.21, vc = 4.99, vp = 4.42,\n              vmax0 = 2.93, km = 1.95, kv = 1.09)\npar_odro <- c(par_odro, vmax_asym = unname(0.262 * par_odro[[\"vmax0\"]]))\n```\n:::\n\n\nThe approved regimen steps up 0.7 mg, 4 mg, 20 mg weekly and then holds at\n160 mg. Peak concentrations after each of those doses, and the clearance\nthe model assigns to them, put every step-up dose on the flat part of the\nMichaelis-Menten curve.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconc  <- 10^seq(-3.5, 2.5, length.out = 400)\ncurve <- tibble(conc, cltot = 0.189 + 2.93/(1.95 + conc)*4.99)\nmarks <- tibble(dose = c(0.7, 4, 20, 160, 320)) |>\n  mutate(conc  = dose/4.99,\n         cltot = 0.189 + 2.93/(1.95 + conc)*4.99,\n         lab   = paste0(dose, \" mg\"))\n\nggplot(curve, aes(conc, cltot)) +\n  geom_line(linewidth = 0.7) +\n  geom_vline(xintercept = 1.95, linetype = 2, colour = \"grey45\") +\n  geom_point(data = marks, size = 2.6, colour = \"#C0392B\") +\n  ggrepel::geom_text_repel(data = marks, aes(label = lab), size = 3.2,\n                           colour = \"#C0392B\", seed = 1) +\n  annotate(\"text\", x = 1.95, y = 0.25, label = \"  km = 1.95 mg/L\",\n           hjust = 0, size = 3.2, colour = \"grey35\") +\n  scale_x_log10() + scale_y_log10() + annotation_logticks() +\n  labs(x = \"Odronextamab concentration (mg/L)\", y = \"Total clearance (L/day)\")\n```\n\n::: {.cell-output-display}\n![Total odronextamab clearance against concentration at the start of treatment, with the peak concentration of each step-up dose marked. The curve is flat below $k_m$, so the first three doses are eliminated by a saturable mechanism at a rate indistinguishable from first-order.](specification_files/figure-html/regime-1.png){width=576}\n:::\n:::\n\n\nThe 0.7 mg dose peaks at 0.14 mg/L, which is $k_m/14$. Simulating that\ndose on its own, with target depletion switched off so that the only\nnonlinearity left is the concentration dependence:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nev_single <- et(amt = 0.7, time = 0) |> et(seq(0, 14, by = 0.02))\nno_deplete <- replace(par_odro, \"kv\", 0)\nas_tibble(rxSolve(odro, no_deplete, ev_single)) |>\n  filter(time %in% c(0.02, 0.5, 1, 2, 3, 7, 14)) |>\n  transmute(`Day` = time,\n            `Concentration (mg/L)` = signif(cc, 3),\n            `Total CL (L/day)` = signif(cltot, 3)) |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|   Day| Concentration (mg/L)| Total CL (L/day)|\n|-----:|--------------------:|----------------:|\n|  0.02|             0.136000|             7.20|\n|  0.50|             0.060200|             7.46|\n|  1.00|             0.026200|             7.59|\n|  2.00|             0.006230|             7.66|\n|  3.00|             0.002560|             7.68|\n|  7.00|             0.000772|             7.68|\n| 14.00|             0.000153|             7.69|\n\n\n:::\n:::\n\n\nTotal clearance moves by 7% while concentration falls 900-fold. A\nMichaelis-Menten elimination, simulated with its own published\nparameters, produces a log-linear profile. Pearce et al. name this as the\nreason TCEs retain linear pharmacokinetics at low doses despite\nhigh-affinity binding, and identify it as the fourth phase of TMDD in the\nPeletier and Gabrielsson classification.\n\n::: {.callout-warning appearance=\"simple\"}\n**The fourth-phase label is borrowed and may not transfer.** Peletier and\nGabrielsson derive their phases for a one-compartment model with no\ndistribution phase and no peripheral compartment. Everything in this\nproject is two-compartment, where a bend in a log-concentration profile can\nbe distribution as easily as target saturation, and where the phases are not\nseparable by inspection. Section 9.5 shows the two-compartment version\nchanging the answer outright. The classification is used here as vocabulary\nfor \"saturable elimination behaving first-order at low concentration\", which\nis arithmetic that holds in any number of compartments, and not as a claim\nthat a TCE profile has four identifiable phases.\n:::\n\n**The verdict on explanation 1: it holds.** The priming dose is too small\nto bend the curve. A visible sharp drop requires a dose that traverses the\nsaturation boundary *during the observed profile*, and the step-up schedule\nis built so that no single dose does that.\n\n## 4. Explanation 2: The Target Sink Is Destroyed During Cycle 1\n\nThe nonlinearity does appear at the full dose, where concentration passes\n$k_m$. By then the target is gone.\n\nSimulating the full approved regimen, against two counterfactuals, shows\nwhere the clearance goes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nev <- et(amt = 0.7, time = 0) |> et(amt = 4, time = 7) |> et(amt = 20, time = 14) |>\n      et(amt = 160, time = seq(21, 77, by = 7)) |> et(seq(0, 84, by = 0.02))\n\nrun <- function(pp, lab) as_tibble(rxSolve(odro, pp, ev)) |> mutate(case = lab)\nsims <- bind_rows(\n  run(par_odro, \"as published\"),\n  run(replace(par_odro, \"kv\", 0), \"target sink never depleted\"),\n  run(replace(par_odro, c(\"vmax0\",\"vmax_asym\"), c(0, 0)),\n      \"no target-mediated elimination\"))\n\ntop <- ggplot(sims, aes(time, cc, colour = case)) +\n  geom_line(linewidth = 0.6) + scale_y_log10() + annotation_logticks(sides = \"l\") +\n  labs(x = NULL, y = \"Concentration (mg/L)\", colour = NULL)\nbot <- ggplot(sims, aes(time, cltot, colour = case)) +\n  geom_line(linewidth = 0.6) + scale_y_log10() + annotation_logticks(sides = \"l\") +\n  labs(x = \"Days since first dose\", y = \"Total clearance (L/day)\", colour = NULL)\n\n(top / bot) + plot_layout(guides = \"collect\") & theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Odronextamab under the 0.7/4/20/160 mg weekly regimen, as published and against two counterfactuals. Upper panel, concentration. Lower panel, total clearance. The published model loses 96% of its clearance over the first three weeks, from 7.2 to 0.30 L/day. With the target sink held fixed it loses only the part that saturation accounts for, and still clears 2.9 times faster than the published model at day 84.](specification_files/figure-html/cl-time-1.png){width=672}\n:::\n:::\n\n\nThe upper panel is what a reviewer of this study would have in front of\nthem. Three curves, each a near-straight line on a log axis within every\ndosing interval, differing only in slope, with nothing that announces a\nsaturable mechanism. The lower panel holds the 25-fold change in clearance,\nand clearance is not an observation.\n\nEvery published TCE population model of an approved drug encodes a decay,\nand each names target depletion or disease response as the cause. The sizes\nare not comparable.\n\n| Drug | Clearance structure | At start | Asymptote | Fold | Decay half-life |\n|:---|:---|---:|---:|---:|---:|\n| Odronextamab, DLBCL | Linear + Michaelis-Menten, $V_{\\max}$ declining | ~5.6 L/d | 0.22 L/d | **26** | **0.64 d** |\n| Odronextamab, follicular | same, with the $K_v$ covariate | | | | 5.8 d |\n| Teclistamab | $CL_1 + CL_2 e^{-K_{DES}t}$ | 0.996 L/d | 0.449 L/d | 2.2 | 23.7 d |\n| Mosunetuzumab | $CL_{\\rm base}\\to CL_{ss}$, exponential | 1.08 L/d | 0.584 L/d | 1.8 | 16.3 d |\n| Talquetamab | Time-independent + time-dependent linear | $t_{1/2}$ 7.56 d | $t_{1/2}$ 12.2 d | 1.6 | not transcribed |\n| Epcoritamab | Quasi-steady-state TMDD | CL/F 0.53 L/d at end of cycle 3 | not transcribed | | concentration-driven |\n| Glofitamab | Linear | 0.6–1 L/d | same | 1.0 | none |\n\n: Size and speed of the decaying clearance component. ⚠️ Transcribed,\nunverified. {tbl-colwidths=\"[17,28,13,12,8,22]\"}\n\n**Two different things are in that table, and only one of them is TMDD.**\n\nOdronextamab in DLBCL loses 96% of its clearance with a half-life of\n**0.64 days**. That is the timescale of killing target-bearing cells, and\nthe magnitude of a target sink that supplies 91 to 97% of clearance at the\npriming dose. It is TMDD.\n\nTeclistamab and mosunetuzumab lose 45 to 55% of their clearance with\nhalf-lives of **24 and 16 days**. Neither timescale is target-cell killing.\nA T-cell engager at an active dose depletes circulating B cells or plasma\ncells within days, not over three weeks, and the teclistamab and\ntalquetamab authors both name the alternative in their own discussions:\nfalling tumor burden, improving disease status, resolving cancer-related\ncachexia. A three-week decay is a tumor shrinking, not a receptor pool\nemptying.\n\nA two-fold time-dependent clearance therefore cannot account for TMDD, and\nthe reason is that it is not trying to. In teclistamab and\nmosunetuzumab the time-dependent term is largely **not measuring TMDD at\nall**. It is measuring disease response, which is why it is small and slow.\n\n### 4a. Where the Target-Mediated Clearance Actually Is\n\nMeasure it against what the same molecule would clear at with no target to\nbind. Odronextamab's own fitted linear clearance, 0.189 L/day, is the\nreference, and its authors call it typical for a monoclonal antibody.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nigg <- 0.189   # L/day, odronextamab's fitted linear CL\ntibble(\n  Drug  = c(\"Teclistamab\", \"Mosunetuzumab\", \"Odronextamab (DLBCL)\"),\n  Vss   = c(5.47, 11.66, 9.41),\n  CL0   = c(0.996, 1.080, 5.620),\n  CLinf = c(0.449, 0.584, 0.219)) |>\n  transmute(\n    Drug,\n    `t1/2 with no target (d)`  = round(log(2)*Vss/igg, 1),\n    `t1/2 at start (d)`        = round(log(2)*Vss/CL0, 1),\n    `t1/2 at steady state (d)` = round(log(2)*Vss/CLinf, 1),\n    `CL0 / IgG CL`             = round(CL0/igg, 1),\n    `CLinf / IgG CL`           = round(CLinf/igg, 1)) |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|Drug                 | t1/2 with no target (d)| t1/2 at start (d)| t1/2 at steady state (d)| CL0 / IgG CL| CLinf / IgG CL|\n|:--------------------|-----------------------:|-----------------:|------------------------:|------------:|--------------:|\n|Teclistamab          |                    20.1|               3.8|                      8.4|          5.3|            2.4|\n|Mosunetuzumab        |                    42.8|               7.5|                     13.8|          5.7|            3.1|\n|Odronextamab (DLBCL) |                    34.5|               1.2|                     29.8|         29.7|            1.2|\n\n\n:::\n:::\n\n\nTeclistamab clears 5.3 times faster at treatment start than a target-free\nantibody of its size, which is 3.8 days of half-life against 20. The 3.8\ndays is the figure Pearce et al. report for teclistamab in patients, so the\narithmetic closes. **That 5-fold is the TMDD, and only a 2.2-fold part of\nit is the time-dependent term.** The rest never decays.\n\n**A candidate for the non-decaying excess, rejected.** The obvious\nexplanation is a standing CD3 sink: a TCE kills antigen-bearing cells and\ndoes not kill T cells, so the CD3 contribution should persist. Section 9\ntests it with a two-pool target depletion model, and the CD3 pool contributes\n13% of clearance at the priming dose and about 0.5% at the therapeutic dose,\nwhere it is saturated. It cannot carry 26% of the budget at any dose. What\nthe non-decaying excess is remains open, and the split of $CL_1$ is:\n\n| Route | L/day | Share | Visible as |\n|:---|---:|---:|:---|\n| Intrinsic IgG catabolism | 0.189 | 19% | $CL_1$ |\n| Non-decaying excess, mechanism not established | 0.260 | 26% | $CL_1$ |\n| Depletable target, BCMA | 0.547 | 55% | $CL_2$, the time-dependent term |\n| **Above intrinsic catabolism** | **0.807** | **81%** | one third of it |\n\n: Teclistamab clearance budget at treatment start, using 0.189 L/day as the\ntarget-free reference. The middle row is a residual, not an estimate of a\nnamed mechanism. {tbl-colwidths=\"[38,11,11,40]\"}\n\n### 4b. Why It Shows Preclinically and Not in Patients\n\nTMDD is reported in cynomolgus monkey for three of the four CD20×CD3\nantibodies, at doses at or below 0.1 mg/kg. Every feature of that\nexperiment is the opposite of the clinical one.\n\n| | Cynomolgus study | Patient study |\n|:---|:---|:---|\n| Target compartment | Healthy, full B-cell pool | Relapsed or refractory, often already depleted |\n| Prior anti-target therapy | None | 44% of the mosunetuzumab cohort carried residual rituximab, 8% obinutuzumab |\n| Dosing | Single dose, then follow | Weekly step-up, redosed before the profile resolves |\n| Sampling | Dense, hours after dosing | Sparse, predose and a few points per week |\n| Assay floor | Set for the dose given | Near the priming-dose concentrations |\n\n: Why the same molecule shows TMDD in one experiment and not the other\n{tbl-colwidths=\"[22,36,42]\"}\n\nThe window is the reason. With a sink half-life of 0.64 days, the full\ntarget-mediated clearance exists for about two days after the first dose,\nand 90% of it is gone by day 2.1. A cynomolgus study samples inside that\nwindow. A patient study takes its next sample at the day-7 predose, by\nwhich time the sink has been gone for five days.\n\nPearce et al. reach the same conclusion from the other direction: their\nmodel under-predicts the observed half-lives of both mosunetuzumab and\nglofitamab in patients, and they speculate that the CD20-mediated\nclearance extrapolated from ofatumumab over-predicts the target burden in\nthese heavily pretreated populations. The patients arrive with less target\nthan the model assumes.\n\n### 4c. Glofitamab, and the Rejected Parameterizations\n\nGlofitamab is the row to read against the other five. It is the one TCE\ngiven after a mandatory 1000 mg obinutuzumab pretreatment, which depletes\nCD20-bearing B cells a week *before* the first glofitamab dose, and its\npublished model is linear with no time-varying term. Remove the target\nbefore the drug arrives and the target-mediated clearance is not there to\nmodel.\n\nTeclistamab's authors tested a quasi-steady-state TMDD parameterization\nand a time-varying soluble BCMA covariate, and rejected both in favor of\nthe empirical exponential decay. Reading why those two failed is what\ntells you whether the empirical form is a convenience or a necessity, and\nit is entry 4 of the reading queue.\n\nOne thing the rejection is *not* evidence of. A time-dependent linear\nclearance is capable of recovering a large target-mediated effect when the\ndata supports it: simulating the odronextamab model under its own regimen\nwith dense cycle-1 sampling and a 0.01 mg/L quantitation limit, and\nrefitting with teclistamab's $CL_1 + CL_2e^{-K_{DES}t}$ form, recovers a\n20-fold clearance change against a true 32-fold. Raise the quantitation\nlimit to 0.10 mg/L and the same fit collapses, driving $CL_1$ to zero. The\nmodel form is adequate. The data underneath it, at the priming dose, is\nwhat decides what can be seen.\n\n**The verdict on explanation 2: it holds for odronextamab and it is why\nTMDD is mis-filed everywhere.** Where the sink is large it empties in two\ndays, inside the window no clinical study samples. Where the decaying term\nis slow and small, it is measuring the tumor rather than the target, and\nthe target-mediated clearance has been absorbed into a linear parameter\nthat names no mechanism.\n\n## 5. Explanation 3: Flip-Flop Kinetics After Subcutaneous Dosing\n\nThe hypothesis is that slow subcutaneous absorption rate-limits the terminal\nslope, so the apparent half-life reports absorption rather than elimination.\nTwo subcutaneous drugs have transcribed absorption rate constants, and they\nanswer differently.\n\n\n::: {.cell}\n\n```{.r .cell-code}\neff_thalf <- function(cl, vc, vp) log(2) * (vc + vp) / cl\n\ntibble(\n  Drug = c(\"Teclistamab\", \"Teclistamab\", \"Elranatamab\"),\n  When = c(\"treatment start\", \"steady state\", \"all times (linear model)\"),\n  `Absorption t1/2 (d)` = signif(log(2) / c(0.133, 0.133, 0.148), 3),\n  `Elimination t1/2 (d)` = signif(c(eff_thalf(0.449 + 0.547, 4.13, 1.34),\n                                    eff_thalf(0.449,         4.13, 1.34),\n                                    eff_thalf(0.335,         4.25, 7.80)), 3)) |>\n  mutate(`Rate-limiting step` =\n           ifelse(`Absorption t1/2 (d)` > `Elimination t1/2 (d)`,\n                  \"absorption (flip-flop)\", \"elimination\")) |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|Drug        |When                     | Absorption t1/2 (d)| Elimination t1/2 (d)|Rate-limiting step     |\n|:-----------|:------------------------|-------------------:|--------------------:|:----------------------|\n|Teclistamab |treatment start          |                5.21|                 3.81|absorption (flip-flop) |\n|Teclistamab |steady state             |                5.21|                 8.44|elimination            |\n|Elranatamab |all times (linear model) |                4.68|                24.90|elimination            |\n\n\n:::\n:::\n\n\nTeclistamab crosses the boundary during treatment. At treatment start\nabsorption is slower than elimination, so the terminal slope after an early\nsubcutaneous dose reports $K_a$; once the time-dependent clearance component\nof Section 4 has decayed, elimination is the slower of the two and the\nordering has reversed. That crossing is a second reason teclistamab's\nhalf-life lengthens with repeated dosing, working in the same direction as\nthe falling clearance.\n\nElranatamab does not cross it. Its absorption half-life of 4.7 days sits\nagainst an elimination half-life near 25 days, so absorption is never\nrate-limiting, and its published half-life of 22 days is elimination being\nreported as elimination.\n\nThree limits on how far the hypothesis carries.\n\n1. **It cannot explain the intravenous drugs.** Mosunetuzumab, glofitamab\n   and odronextamab have no absorption phase and show the same absence of\n   visible nonlinearity. Explanation 3 is an additional flattening\n   mechanism for some subcutaneous molecules, not the reason the class\n   looks the way it does.\n2. **It is contingent on where in treatment the sample was drawn.** The\n   same drug is flip-flop in week 1 and not in week 8, because the quantity\n   it is being compared against is itself changing. Any statement that a TCE\n   does or does not show flip-flop kinetics has to name the time.\n3. **Two cases is not a survey.** Epcoritamab reports a median time to\n   maximum concentration of 4 days after the first full dose, consistent\n   with slow absorption, but its absorption rate constant has not been\n   transcribed here. Talquetamab uses a sequential zero- then first-order\n   absorption, which does not reduce to a single $K_a$. Filling the\n   absorption column of [PK parameters](pk-parameters.qmd) is what turns\n   this section from two worked examples into a finding.\n\n**The verdict on explanation 3: it holds for teclistamab early in\ntreatment, fails for elranatamab, and cannot apply to the intravenous\ndrugs.** It is a contributing mechanism with a narrow domain, not the\nexplanation.\n\n## 6. Explanation 4: Sampling and the Quantitation Limit\n\nUntestable from published summaries, and stated here so that it is not\nmistaken for a settled negative.\n\nThree features of how TCE pharmacokinetic data is collected would hide a\nconcentration drop that was there.\n\n- **CD3 internalizes with a half-life near an hour.** The fastest\n  target-mediated phase is over within a day. Cycle 1 sampling in these\n  studies is typically predose, end of infusion, and then a small number\n  of points across the following week.\n- **Priming-dose concentrations sit near the assay limit.** The\n  odronextamab simulation above puts the 0.7 mg profile between 0.14 and\n  0.005 mg/L. Kovalenko et al. excluded 3.4% of post-dose records as below\n  the limit of quantitation, and those records are disproportionately the\n  early low-dose ones, which is exactly where the curvature would be.\n- **The step-up schedule redoses before the profile resolves.** Each\n  weekly dose interrupts the decline of the previous one.\n\nWhat would settle it is a densely sampled single priming dose with a\nlow-limit assay, and the studies that could produce it are the ones\nalready run. A first-in-human dose escalation collects that data at the\nlowest cohorts and reports a summary.\n\n## 7. The Arithmetic of the CD3 Sink\n\nSection 3 argues the priming dose is small relative to $k_m$. This section\nasks the blunter version: how much drug does the CD3 pool actually consume?\n\n\n::: {.cell}\n\n```{.r .cell-code}\navogadro  <- 6.022e23\ncd3_per_T <- 5e4     # receptors per T cell\ntcell_uL  <- 1500    # T cells per uL of blood\nblood_L   <- 5\nmw        <- 1.5e5   # g/mol\nkint      <- 0.014   # per minute\n\ntcells <- tcell_uL * 1e6 * blood_L\nr_mol  <- tcells * cd3_per_T / avogadro\nr_mg   <- r_mol * mw * 1000\nvmax_mg_day <- r_mol * kint * 60 * 24 * mw * 1000\n\ntibble(\n  Quantity = c(\"T cells in blood\",\n               \"CD3 receptors in blood (nmol)\",\n               \"Drug for 1:1 occupancy of that pool (mg)\",\n               \"CD3 internalization half-life (min)\",\n               \"Maximum CD3-mediated elimination (mg/day)\"),\n  Value = c(format(tcells, digits = 3, scientific = TRUE),\n            signif(r_mol * 1e9, 3),\n            signif(r_mg, 3),\n            signif(log(2)/kint, 3),\n            signif(vmax_mg_day, 3))) |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|Quantity                                  |Value   |\n|:-----------------------------------------|:-------|\n|T cells in blood                          |7.5e+09 |\n|CD3 receptors in blood (nmol)             |0.623   |\n|Drug for 1:1 occupancy of that pool (mg)  |0.0934  |\n|CD3 internalization half-life (min)       |49.5    |\n|Maximum CD3-mediated elimination (mg/day) |1.88    |\n\n\n:::\n:::\n\n\nNote the discrepancy in the internalization half-life. Pearce et al. give\nthe rate as 1.4% per minute and describe the corresponding half-life as\n\"about 36 min\"; $\\ln 2 / 0.014$ is 49.5 minutes. The 1.4% figure is used\nabove because it is the one their model consumes. Which of the two is the\nmeasured quantity in the underlying source is an open check.\n\nAgainst the epcoritamab regimen, which primes at 0.16 mg and reaches a full\ndose of 48 mg weekly:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(Dose = c(\"0.16 mg priming\", \"0.8 mg intermediate\", \"48 mg full\")) |>\n  mutate(mg = c(0.16, 0.8, 48),\n         `Multiples of the standing CD3 pool` = signif(mg / r_mg, 2),\n         `Percent of one week's internalization capacity` =\n           signif(100 * mg / (7 * vmax_mg_day), 2)) |>\n  select(-mg) |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|Dose                | Multiples of the standing CD3 pool| Percent of one week's internalization capacity|\n|:-------------------|----------------------------------:|----------------------------------------------:|\n|0.16 mg priming     |                                1.7|                                            1.2|\n|0.8 mg intermediate |                                8.6|                                            6.1|\n|48 mg full          |                              510.0|                                          360.0|\n\n\n:::\n:::\n\n\nThe priming dose is a few multiples of the standing receptor pool and a\nrounding error against the pool's weekly turnover. The sink swallows it. The\nfull dose is several times the weekly capacity of the blood CD3 pool, which\nis where the nonlinearity finally shows.\n\nThe calculation counts only circulating T cells. Whole-body T cells are\nroughly fifty times the blood pool, and if a TCE reached all of them the\ncapacity would be near 100 mg/day and no clinical dose would ever saturate\nCD3. Observed half-lives of a week say it does not. **How much of the tissue\nT-cell pool is accessible to a TCE is the open question this calculation\nexposes**, and it is the one to put to the Pearce model, which assumes blood\ncounts throughout.\n\n## 8. Order of Work\n\n1. **Check the transcribed parameters against the printed tables.** Every\n   number in Sections 3, 4 and 5 is ⚠️ in [References](references.qmd).\n   The odronextamab simulation reproduces a baseline total clearance of\n   7.1 L/day where the paper reports a population median of 5.4 L/day, and\n   whether that gap is the covariate model, between-subject variability,\n   or a transcription error is unresolved.\n2. **Fill the parameter table.** [PK parameters](pk-parameters.qmd) has\n   eight drugs and four complete entries. Epcoritamab's quasi-steady-state\n   parameters and talquetamab's time-dependent clearance are the two\n   highest-value gaps, because they are the two published models with a\n   structure nothing else here duplicates.\n3. **Reproduce Figure 2 of Pearce et al.** Their simulation of half-life\n   against CD3 affinity, from 1000 nM to 1 nM at a fixed 0.01 mg/kg dose,\n   is the generic version of Section 3 and is reproducible from the\n   equations in their methods.\n4. **Test explanation 4 against one dense profile.** Any first-in-human\n   report with individual concentration-time data at the lowest cohort\n   would do.\n5. **Write the note to Bill Denney.** Section 4 of\n   [PK parameters](pk-parameters.qmd) lists what `nlmixr2lib` is missing\n   and is already in a form that can be sent.\n\n## 9. Simulation Study: Is the Sharp Drop There and Unobserved?\n\nSections 3 and 4 argue from published fits. This section builds a mechanism,\nsimulates it, and asks whether the argument survives. No quantitative systems\npharmacology model, no trimer, no cytokine cascade. Two target pools with\nturnover, quasi-steady-state binding, and drug-driven killing of the pool\nthat the drug is supposed to kill.\n\n$$\n\\frac{dA_c}{dt} = -\\frac{CL}{V_c}A_c-\\frac{Q}{V_c}A_c+\\frac{Q}{V_p}A_p\n- k_{int}^{CD3}R_{CD3}\\frac{C}{K_{ss}^{CD3}+C}V_c\n- k_{int}^{TAA}R_{TAA}\\frac{C}{K_{ss}^{TAA}+C}V_c\n$$\n$$\n\\frac{dR_{CD3}}{dt}=k_{deg}\\!\\left(R^0_{CD3}-R_{CD3}\\right)-k_{int}^{CD3}R_{CD3}\\frac{C}{K_{ss}^{CD3}+C}\n$$\n$$\n\\frac{dR_{TAA}}{dt}=k_{deg}\\!\\left(R^0_{TAA}-R_{TAA}\\right)-k_{int}^{TAA}R_{TAA}\\frac{C}{K_{ss}^{TAA}+C}-k_{\\rm kill}R_{TAA}\\frac{C}{K_{ss}^{TAA}+C}\n$$\n\nCD3 turns over and is not killed, because a T-cell engager does not kill T\ncells. The tumor antigen turns over and is killed, because that is the\nmechanism of action.\n\n**Scope, narrowed here and for the rest of this section.** Molecules with an\nintact Fc domain and therefore neonatal Fc receptor recycling. Blinatumomab,\ntebentafusp and the albumin-binding formats are out: at 54 kDa and without\nan Fc, blinatumomab clears in hours whatever it binds, and nothing below is\nabout them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntruth <- rxode2({\n  cc      <- central/vc\n  occ_cd3 <- cc/(kss_cd3 + cc)\n  occ_taa <- cc/(kss_taa + cc)\n  cl_cd3  <- kint_cd3*r_cd3*vc/(kss_cd3 + cc)\n  cl_taa  <- kint_taa*r_taa*vc/(kss_taa + cc)\n  cltot   <- cl + cl_cd3 + cl_taa\n  d/dt(central)    <- -cl/vc*central - q/vc*central + q/vp*peripheral -\n                       kint_cd3*r_cd3*vc*occ_cd3 - kint_taa*r_taa*vc*occ_taa\n  d/dt(peripheral) <-  q/vc*central - q/vp*peripheral\n  d/dt(r_cd3)      <-  kdeg_cd3*(r_cd3_0 - r_cd3) - kint_cd3*r_cd3*occ_cd3\n  d/dt(r_taa)      <-  kdeg_taa*(r_taa_0 - r_taa) - kint_taa*r_taa*occ_taa -\n                       kkill*r_taa*occ_taa\n  r_cd3(0) <- r_cd3_0\n  r_taa(0) <- r_taa_0\n})\n\n## CD3 arm from Pearce et al., independent of any fitted popPK:\n## 50,000 CD3 per T cell, 1500 T cells/uL, 5 L blood, 1.4%/min internalisation.\ncd3_mg <- 0.0934                       # mg of TCE for 1:1 occupancy of blood CD3\n## TAA arm from odronextamab's fitted Michaelis-Menten sink: Vmax0/km*Vc.\np_sim <- c(cl = 0.189, vc = 4.99, vp = 4.42, q = 1.21,\n           kss_cd3 = 10*1e-9*150000*1000,   # 10 nM CD3 affinity, as mg/L\n           r_cd3_0 = cd3_mg/4.99, kint_cd3 = 0.014*60*24, kdeg_cd3 = log(2)/1,\n           kss_taa = 1.95, kint_taa = 1, kdeg_taa = log(2)/3, kkill = 1.09)\np_sim[\"r_taa_0\"] <- 7.50*p_sim[[\"kss_taa\"]]/(p_sim[[\"kint_taa\"]]*p_sim[[\"vc\"]])\n```\n:::\n\n\n### 9.1 The Control: The Same Molecule Without the CD3 Arm\n\nSwitch the CD3 pool off and what remains is a B-cell depleting antibody with\nthe same CD20 affinity, the same target pool, the same Fc and the same\ndisposition. Run both at a T-cell engager priming dose and at a\nrituximab-like dose, and the confound between *being a T-cell engager* and\n*being dosed at a microgram-per-kilogram level* comes apart.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhalf_life <- function(d, t1, t2) {\n  w <- dplyr::filter(d, time >= t1, time <= t2, cc > 0)\n  unname(-log(2)/coef(lm(log(cc) ~ time, data = w))[2])\n}\none <- function(cd3, dose, label) {\n  p <- p_sim; if (!cd3) p[\"r_cd3_0\"] <- 0\n  d <- as_tibble(rxSolve(truth, p, et(amt = dose, time = 0) |> et(seq(0, 42, by = 0.005))))\n  tibble(Molecule = label, `Dose` = paste(dose, \"mg\"),\n         `C0 (mg/L)` = signif(d$cc[2], 3),\n         `C0 / Kss`  = signif(d$cc[2]/p[[\"kss_taa\"]], 3),\n         `t1/2 0-1 d`   = round(half_life(d, 0.01, 1), 2),\n         `t1/2 3-7 d`   = round(half_life(d, 3, 7), 2),\n         `t1/2 21-42 d` = round(half_life(d, 21, 42), 2)) |>\n    mutate(`Curvature ratio` = round(`t1/2 21-42 d`/`t1/2 0-1 d`, 1))\n}\nbind_rows(\n  one(TRUE,  0.7,  \"T-cell engager\"),\n  one(FALSE, 0.7,  \"B-cell depleting mAb\"),\n  one(TRUE,  1000, \"T-cell engager\"),\n  one(FALSE, 1000, \"B-cell depleting mAb\")) |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|Molecule             |Dose    | C0 (mg/L)| C0 / Kss| t1/2 0-1 d| t1/2 3-7 d| t1/2 21-42 d| Curvature ratio|\n|:--------------------|:-------|---------:|--------:|----------:|----------:|------------:|---------------:|\n|T-cell engager       |0.7 mg  |     0.139|   0.0713|       0.39|       2.42|         2.93|             7.5|\n|B-cell depleting mAb |0.7 mg  |     0.139|   0.0713|       0.43|       2.39|         3.00|             7.0|\n|T-cell engager       |1000 mg |   200.000| 103.0000|       2.73|      11.20|        30.75|            11.3|\n|B-cell depleting mAb |1000 mg |   200.000| 103.0000|       2.73|      11.21|        30.94|            11.3|\n\n\n:::\n:::\n\n\n**The CD3 arm makes no difference to the shape.** At 0.7 mg the engager and\nthe plain antibody give curvature ratios of 7.5 and 7.0; at 1000 mg both give\n11.3. Whatever is going on, it is not something T-cell engagers do that\nantibodies do not. It is what the *dose* does.\n\n**And the sharp drop is there.** At 0.7 mg the apparent half-life is 0.39\ndays over the first day and 2.9 days from week three, a 7.5-fold steepening.\nThat is the elbow. It lives between 0.14 and 0.01 mg/L and it is over inside\n24 hours.\n\n### 9.2 Where the Elbow Sits at Each Dose\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndoses <- c(0.7, 20, 160, 1000)\nprof <- lapply(doses, function(dd) {\n  as_tibble(rxSolve(truth, p_sim, et(amt = dd, time = 0) |> et(seq(0, 42, by = 0.02)))) |>\n    mutate(dose = factor(paste(dd, \"mg\"), levels = paste(doses, \"mg\")))\n}) |> bind_rows()\n\nggplot(prof, aes(time, cc, colour = dose)) +\n  geom_hline(yintercept = 1.95, linetype = 2, colour = \"grey45\") +\n  annotate(\"text\", x = 41, y = 1.95, label = \"Kss\", hjust = 1, vjust = -0.5,\n           size = 3.2, colour = \"grey35\") +\n  geom_line(linewidth = 0.6) +\n  scale_y_log10() + annotation_logticks(sides = \"l\") +\n  labs(x = \"Days after a single dose\", y = \"Concentration (mg/L)\", colour = NULL)\n```\n\n::: {.cell-output-display}\n![Single dose of the same molecule at four dose levels, with the CD3 arm on. Concentrations are scaled to the dose so the shapes can be compared. The horizontal line is $K_{ss}$ for the tumor antigen. A profile bends where it crosses that line; the 0.7 mg profile starts below it and never does.](specification_files/figure-html/elbow-1.png){width=672}\n:::\n:::\n\n\nThe 1000 mg profile is the textbook picture: flat while the target is\nsaturated, then bending as concentration falls toward $K_{ss}$. The 0.7 mg\nprofile has its entire elbow in the first hours, below the bottom of the\naxis a clinical assay can reach.\n\n### 9.5 Where the Target Sits, and Why It Decides the Answer\n\nEvery model so far, published and simulated, puts the target in the central\ncompartment. For a T-cell engager that is the wrong place. About 2% of T\ncells circulate; BCMA sits on plasma cells in bone marrow; CD20 sits on B\ncells in lymph nodes, marrow and spleen. The target is overwhelmingly\nperipheral, and the drug has to distribute before it can meet it.\n\nRun the same model twice with the antigen pool moved, total capacity matched\nat 14.6 mg/day, and the placement decides the result at exactly one dose\nlevel.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmk <- function(where) {\n  drv <- if (where == \"central\") \"cc\" else \"cp\"\n  vv  <- if (where == \"central\") \"vc\" else \"vp\"\n  rxode2(paste0('\n    cc <- central/vc\n    cp <- peripheral/vp\n    occ_cd3 <- cc/(kss_cd3 + cc)\n    occ_taa <- ', drv, '/(kss_taa + ', drv, ')\n    cltot   <- cl + kint_cd3*r_cd3*vc/(kss_cd3+cc) + kint_taa*r_taa*', vv, '/(kss_taa+', drv, ')\n    loss    <- kint_taa*r_taa*', vv, '*occ_taa\n    d/dt(central)    <- -cl/vc*central - q/vc*central + q/vp*peripheral -\n                         kint_cd3*r_cd3*vc*occ_cd3 ',\n                         if (where == \"central\") \"- loss\" else \"\", '\n    d/dt(peripheral) <-  q/vc*central - q/vp*peripheral ',\n                         if (where == \"peripheral\") \"- loss\" else \"\", '\n    d/dt(r_cd3) <- kdeg_cd3*(r_cd3_0 - r_cd3) - kint_cd3*r_cd3*occ_cd3\n    d/dt(r_taa) <- kdeg_taa*(r_taa_0 - r_taa) - kint_taa*r_taa*occ_taa - kkill*r_taa*occ_taa\n    r_cd3(0) <- r_cd3_0\n    r_taa(0) <- r_taa_0'))\n}\ncapacity <- 7.50 * 1.95                       # mg/day at saturation, matched\nloc <- function(where, dose) {\n  m <- mk(where)\n  pp <- p_sim\n  pp[\"r_taa_0\"] <- capacity/(pp[[\"kint_taa\"]] *\n                             pp[[if (where == \"central\") \"vc\" else \"vp\"]])\n  d <- as_tibble(rxSolve(m, pp, et(amt = dose, time = 0) |> et(seq(0, 42, by = 0.005))))\n  tibble(`Target in` = where, Dose = paste(dose, \"mg\"),\n         `t1/2 0-1 d`   = round(half_life(d, 0.01, 1), 2),\n         `t1/2 21-42 d` = round(half_life(d, 21, 42), 2)) |>\n    mutate(`Curvature ratio` = round(`t1/2 21-42 d`/`t1/2 0-1 d`, 1))\n}\nbind_rows(lapply(c(0.7, 160, 1000), function(d)\n  bind_rows(loc(\"central\", d), loc(\"peripheral\", d)))) |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|Target in  |Dose    | t1/2 0-1 d| t1/2 21-42 d| Curvature ratio|\n|:----------|:-------|----------:|------------:|---------------:|\n|central    |0.7 mg  |       0.39|         2.93|             7.5|\n|peripheral |0.7 mg  |       1.78|         1.42|             0.8|\n|central    |160 mg  |       2.39|        13.02|             5.4|\n|peripheral |160 mg  |       2.75|        13.48|             4.9|\n|central    |1000 mg |       2.73|        30.75|            11.3|\n|peripheral |1000 mg |       2.79|        30.77|            11.0|\n\n\n:::\n:::\n\n\n**At the priming dose the elbow exists only if the target is central.** With\nthe antigen in the central compartment the curvature ratio is 7.5; move it to\nthe peripheral compartment and it is 0.8, which is a straight line. At 160\nand 1000 mg the placement barely registers, 5.5 against 4.9 and 11.3 against\n11.0.\n\nThe reason is a race between two timescales. Distribution has a half-life of\n$\\ln 2/(Q/V_c+Q/V_p)$ = 1.34 days. A central target eliminates the priming\ndose with a half-life of 0.39 days, three times faster than the drug can\nreach the periphery, so the elbow happens before distribution does. A\nperipheral target cannot eliminate what has not arrived yet, so the\ntarget-mediated loss is spread across the distribution phase and there is no\nelbow left to see. At a saturating dose the target is destroyed in a day\neither way and the race never happens.\n\nThis is the two-compartment effect that the Peletier and Gabrielsson phases\ncannot express, and it changes the conclusion of Section 9.3 rather than\ndecorating it.\n\n### 9.3 The Hypothesis That Survives\n\nStated so that it can be shot at.\n\n> **A T-cell engager shows exactly the target-mediated disposition its\n> affinity and target burden imply, and three things in series keep it off\n> the page. The priming dose never puts the concentration above $K_{ss}$, so\n> the elimination is saturable but arithmetically first-order. The target is\n> mostly peripheral, so what elbow the arithmetic allows is spread across a\n> 1.3-day distribution phase instead of happening in the first hours. And the\n> target is destroyed within a day or two, so by the therapeutic dose, where\n> concentrations finally exceed $K_{ss}$, there is no sink left to bend the\n> curve. None of the three has anything to do with CD3.**\n\nThe middle clause carries most of the weight. Without it the hypothesis\npredicts a sharp drop in the first 24 hours that nobody has looked for; with\nit, there is no sharp drop to find, and the prediction changes from \"sample\nharder\" to \"the profile really is log-linear.\"\n\nThe predictions it makes, and how each could fail.\n\n| Prediction | Fails if |\n|:---|:---|\n| A B-cell depleting mAb dosed at 0.7 mg shows the same elbow as a TCE at 0.7 mg | The engager's profile is steeper, which would mean CD3 contributes |\n| Dense sampling over the first 24 h after a TCE priming dose, with a sub-ng/mL assay, shows a half-life under a day **if the target is central** | The observed early half-life matches the reported terminal one, which would instead support a peripheral target |\n| Moving the antigen pool to the peripheral compartment removes the elbow at a priming dose and not at a saturating one | The placement changes nothing at either dose |\n| A TCE given without step-up, straight to the full dose, shows the mAb-like elbow as concentration decays through $K_{ss}$ | The profile is log-linear at the full dose too |\n| Obinutuzumab pretreatment removes the elbow from a first glofitamab dose | Glofitamab shows an elbow anyway |\n\n: Predictions of the surviving hypothesis {tbl-colwidths=\"[62,38]\"}\n\nRow 1 is already simulated above. Row 4 is already observed: glofitamab is\npretreated and its published model is linear.\n\n### 9.4 What the Round-Trip Falsified\n\nThe hypothesis this section started from was that the clinical sampling\nschedule hides a large target-mediated clearance, so a population fit reports\na small time-dependent term instead. Simulating the odronextamab regimen from\nthe mechanism above, sampling at predose and post-infusion times with a 0.10\nmg/L quantitation limit, and refitting with teclistamab's\n$CL_1+CL_2e^{-K_{DES}t}$ form recovers a 25-fold clearance change against a\n40-fold truth.\n\n**The clinical schedule does see it.** The published odronextamab model\nreports 26-fold, which is what this round-trip predicts, so nothing is being\nhidden there. That leaves teclistamab's 2.2-fold and mosunetuzumab's 1.8-fold\nneeding a different explanation from sampling: a genuinely smaller target\npool in heavily pretreated myeloma and lymphoma, a narrower dose range, or\nsubcutaneous absorption smearing the early profile. Which of those it is, is\nthe next simulation and is not done.\n",
    "supporting": [
      "specification_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}