{
  "hash": "e5b8a98a8364d4f6e7e24833ad317eaf",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Sizing Studies for Dose-Response Characterization\"\nsubtitle: \"How many patients an expansion cohort needs to see a dose-response or biomarker-response relationship\"\ndescription: >\n  Four approaches to sizing a Phase 1/2 oncology cohort against a\n  dose-response or biomarker-response endpoint: Frank Harrell's p < m/15\n  rule, Richard Riley's four-question framework, worked binary and\n  continuous examples, and why a continuous endpoint is usually the\n  practical choice.\ncategories: [PMX guide]\ndate: last-modified\nexecute:\n  freeze: auto\n  warning: false\n  message: false\ntoc: true\ntoc-depth: 2\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(xgxr)\n\nset.seed(12345)\nxgx_theme_set()\nknitr::opts_chunk$set(fig.height = 4, fig.width = 5)\n```\n:::\n\n\n**This estimates how many patients a cohort needs to characterize a\ndose-response or biomarker-response relationship with useful precision.** It\ndoes not size a study to reject a null hypothesis that two doses are the\nsame — Section 1 explains why that is usually the wrong question — and it\ndoes not cover Phase 3 confirmatory sizing.\n\n## 1. Why the Usual Power Calculation Is the Wrong Question\n\nThe main purpose of a Phase 1 study is to assess the safety of a drug. It is\nimportant to start from a first-in-human dose expected to be safe, and the\ngoal is often to identify a maximum tolerated dose (MTD), though for many\nbiologics — pembrolizumab and nivolumab, for example — the drug is safe\nenough across the tested range that an MTD cannot be identified.\n\nAfter the MTD, or some other maximum allowable dose set by a constraint such\nas manufacturability or cost of goods, the next step is choosing the dose or\ndoses to test in expansion cohorts, and how many patients each cohort needs.\nThat data then informs the dose or doses carried into later studies. The\nFDA's 2023 draft guidance on dose optimization in oncology trials states that\n\"the trial should be sized to allow for sufficient assessment of activity,\nsafety, and tolerability for each dosage. The trial does not need to be\npowered to demonstrate statistical superiority of a dosage or statistical\nnon-inferiority among the dosages\" ([FDA\n2023](https://www.fda.gov/media/164555/download)), without saying what\n\"sufficient assessment\" means.\n\nThree considerations bear on choosing the number and size of the expansion\ncohorts:\n\n- **The goal is generally not to reject the null hypothesis that two doses\n  are identical.** At reasonable dose choices, most drugs show some\n  difference in safety and efficacy between two doses; the question is how\n  large that difference is and whether it is detectable. Pembrolizumab and\n  nivolumab are the notable exception, where both tested doses saturated\n  PD-1.\n- **The FDA restricts expansion cohorts to at most 40 patients** in solid\n  tumor indications, or 20 in a hematological malignancy rare enough to\n  support initiating efficacy trials on a smaller efficacy database ([FDA\n  2022](https://www.fda.gov/media/115172/download)).\n- **The FDA recommends randomization** for comparing activity across\n  different dosing regimens within a cohort ([FDA\n  2022](https://www.fda.gov/media/115172/download)).\n\nOn efficacy assessment specifically, the FDA guidance states that \"the\nanalysis plan for each expansion cohort should contain adequate information\njustifying the planned sample size based on the cohort objectives. For those\ncohorts evaluating antitumor activity, the plans should specify the\nmagnitude of antitumor activity that would warrant further evaluation of the\ndrug, for example by specifying the precision and power considerations for\ndetection of clinically meaningful antitumor activity. In general, in a\nnonrandomized cohort, assessment of antitumor activity is determined using a\n[Simon two-stage design](https://blog.statsols.com/simons-two-stage-design)\nor other designs (e.g., Bayesian statistical design) to limit exposure of\nadditional subjects to a potentially ineffective drug\" ([FDA\n2022](https://www.fda.gov/media/115172/download)).\n\n## 2. Estimating Dose-Response With Sufficient Precision\n\n### Methodology\n\nThe FDA guidance ([FDA 2022](https://www.fda.gov/media/115172/download))\ncaps expansion cohorts at 20 to 40 patients. Could a leaner study still learn\nenough to tell which of two doses is better to carry forward, especially\nwith a validated biomarker that predicts long-term response well? Four\napproaches to sizing such a study follow.\n\n### Frank Harrell's m/15 Heuristic\n\nIn *Regression Modeling Strategies*, Section 4.4 ([Harrell\n2015](https://hbiostat.org/rmsc/)), Frank Harrell recommends that the number\nof model parameters $p$ stay below one fifteenth of the effective sample\nsize $m$: $p < m/15$, where $m$ is:\n\n- For a continuous endpoint, the total number of patients.\n- For a binary endpoint, the smaller of the number of responses and the\n  number of non-responses.\n- For a time-to-event endpoint, the number of failures.\n- For an ordinal endpoint, a calculation slightly more complex than the\n  above, not covered here.\n\n### Richard Riley's Four Questions\n\nA more rigorous set of criteria for the minimum sample size of a prediction\nmodel is set out in [Riley et al.\n2020](https://doi.org/10.1136/bmj.m441), with the full derivations in two\ncompanion papers, for continuous endpoints ([Riley et al.\n2019a](https://doi.org/10.1002/sim.7993)) and for binary and\ntime-to-event endpoints ([Riley et al.\n2019b](https://doi.org/10.1002/sim.7992)). When a study is designed to use\nmultiple factors to predict response — dose and biomarker expression,\nsay — four questions should set the sample size:\n\n1. What sample size gives a precise estimate of the overall outcome risk or\n   mean outcome value?\n2. What sample size gives predicted values with a small mean error across\n   all individuals?\n3. What sample size keeps the required shrinkage of predictor effects small,\n   reducing the risk of overfitting?\n4. What sample size keeps the optimism in apparent model fit small — that\n   is, keeps the calculated $R^2$ close to the true $R^2$, which also\n   reduces overfitting?\n\nOne more question in this context: is 40 patients per arm enough to characterize\nthe dose-response relationship? For a binary or categorical endpoint, 40 may\nnot be, though it is still a reasonable starting point.\n\n### Trial Simulation\n\nSection 10.2.3 of [Harrell 2015](https://hbiostat.org/rmsc/) gives a trial\nsimulation calculation for a binary endpoint depending on one variable: pick\nthe sample size so the expected maximum error in the estimated probability\nof response, given the variable, stays under some value. As with the\napproaches above, the goal is not to estimate power and accept or reject a\nnull hypothesis — it is to estimate the function relating the independent\nvariables to the endpoint, to within a stated error. Since the goal of a\nPhase 1-2 study is to learn the dose-exposure-biomarker-response\nrelationship for safety and efficacy, minimizing the error in the model\nprediction is a reasonable criterion for the required study size, though\nthis document does not explore the approach further.\n\n## 3. Binary Response Example: Overall Response Rate\n\n### Harrell's Rule of Thumb\n\nFor a dose-response model, at least two parameters are needed (a linear\nmodel, with slope and intercept), and ideally three (an Emax model, with\n$E_0$, $E_\\text{max}$, and $ED_{50}$). Applying Harrell's $p < m/15$ rule,\nwhere the probability of response $p_\\text{resp} \\le 0.5$:\n\n$$\n\\begin{align*}\np & < \\frac{m}{15} = \\frac{p_\\text{resp} \\cdot n}{15} \\\\\nn & > \\frac{15\\,p}{p_\\text{resp}}\n\\end{align*}\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(\n  model     = c(\"Linear\", \"Linear\", \"Emax\", \"Emax\"),\n  p         = c(2, 2, 3, 3),\n  prob_resp = c(0.2, 0.5, 0.2, 0.5)\n) |>\n  mutate(n_patients = round(15 * p / prob_resp)) |>\n  knitr::kable(caption = \"Minimum patients by model and response rate\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Minimum patients by model and response rate\n\n|model  |  p| prob_resp| n_patients|\n|:------|--:|---------:|----------:|\n|Linear |  2|       0.2|        150|\n|Linear |  2|       0.5|         60|\n|Emax   |  3|       0.2|        225|\n|Emax   |  3|       0.5|         90|\n\n\n:::\n:::\n\n\nThe minimum is 60 patients, for a linear dose-response model and a 50%\nresponse rate. A study cannot generally count on a linear model being\nsufficient, and should plan for the possibility that an Emax model is\nrequired — in which case 150 to 225 patients are needed, more than most\nfirst-in-human studies enroll.\n\n### Riley's Approach\n\nUsing the more rigorous approach for a binary outcome ([Riley et al.\n2019b](https://doi.org/10.1002/sim.7992)), the 95% confidence interval for\nan event rate $p$ is\n\n$$\np \\pm \\delta, \\quad \\delta = 1.96 \\sqrt{\\frac{p(1-p)}{n}}\n$$\n\nSolving for $n$:\n\n$$\nn = \\left( \\frac{1.96}{\\delta} \\right)^2 p(1-p)\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(delta = c(0.05, 0.05, 0.1, 0.1), p = c(0.2, 0.5, 0.2, 0.5)) |>\n  mutate(n = round((1.96 / delta)^2 * p * (1 - p))) |>\n  knitr::kable(caption = \"Patients needed for a given confidence-interval width\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Patients needed for a given confidence-interval width\n\n| delta|   p|   n|\n|-----:|---:|---:|\n|  0.05| 0.2| 246|\n|  0.05| 0.5| 384|\n|  0.10| 0.2|  61|\n|  0.10| 0.5|  96|\n\n\n:::\n:::\n\n\nAt $\\delta = 0.05$, over 200 patients are needed, impractical for a\nfirst-in-human oncology study. At $\\delta = 0.1$, 60 to 100 patients is more\nreasonable — but that is only the calculation for the overall event rate in\none arm. If the response rate between two dose groups is expected to differ\nby only 10 to 20 percentage points, $\\delta = 0.1$ is too wide to detect\nthat difference.\n\n### Why a Binary Endpoint Is Not Enough\n\nBoth the Harrell rule of thumb and the Riley approach put the sample size\nneeded to estimate a binary dose-response relationship in the hundreds of\npatients. This is why, when using a first-in-human oncology trial to select\ndoses for further study, a continuous endpoint is needed: it gives greater\nprecision for detecting a difference between two doses with the same number\nof patients.\n\n## 4. Continuous Response Example: Percent Change in Tumor Size\n\n### Example Data\n\nSizing a study for a continuous endpoint needs some knowledge of the\nendpoint's properties. Below, an Emax model is fit to percent change in\ntumor size at the first on-treatment assessment, in 61 patients from a\nsynthetic Phase 1/2 oncology dataset (see [the project\nindex](index.qmd#data) for what it holds).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- readRDS(\"../../data/synthetic/dose-response/emax_tumor_size.rds\") |>\n  rename(Dose = Average_Dose)\n\nmod <- stats::nls(\n  Tumor_Pct_Change ~ E0 + Emax * Dose / (ED50 + Dose),\n  data  = data,\n  start = list(E0 = 40, Emax = -120, ED50 = 200)\n)\n\ndata <- data |>\n  mutate(Tumor_Pct_Change_Pred = predict(mod))\n\nsd0      <- sd(data$Tumor_Pct_Change)\nsd_tumor <- sd(data$Tumor_Pct_Change - data$Tumor_Pct_Change_Pred)\nr2       <- 1 - sd_tumor^2 / sd0^2\n\nggplot(data, aes(x = Dose, y = Tumor_Pct_Change)) +\n  geom_point() +\n  xgx_stat_smooth(\n    method = \"nlsLM\", formula = y ~ E0 + Emax * x / (ED50 + x),\n    method.args = list(start = list(Emax = -120, ED50 = 200, E0 = 40)),\n    se = TRUE\n  ) +\n  labs(\n    x = \"Average daily dose before first assessment\",\n    y = \"Percent change in tumor size\\nat first assessment\",\n    title = paste0(\n      \"N = \", nrow(data), \", SD = \", signif(sd_tumor, 3),\n      \"%, R² = \", signif(r2, 3)\n    )\n  ) +\n  scale_y_continuous(limits = c(-100, 60), breaks = seq(-100, 60, by = 20))\n```\n\n::: {.cell-output-display}\n![](sizing-studies_files/figure-html/unnamed-chunk-3-1.png){width=480}\n:::\n:::\n\n\n### Harrell's Rule of Thumb\n\nFor a continuous endpoint, Harrell's rule needs only 15 patients per\nparameter — a much smaller requirement than for a binary endpoint — with 30\nto 45 patients needed for the linear and Emax models.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(model = c(\"Linear\", \"Emax\"), p = c(2, 3)) |>\n  mutate(n_patients = round(15 * p)) |>\n  knitr::kable(caption = \"Minimum patients by model, continuous endpoint\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Minimum patients by model, continuous endpoint\n\n|model  |  p| n_patients|\n|:------|--:|----------:|\n|Linear |  2|         30|\n|Emax   |  3|         45|\n\n\n:::\n:::\n\n\n### Riley's Approach, Four Steps\n\nThe calculations below directly implement [Riley et al.\n2019a](https://doi.org/10.1002/sim.7993). The reference explains each\ncalculation in full; the summary here does not.\n\n#### Step 1: Calculating Shrinkage\n\nFor a 3-parameter model, an apparent $R^2$ within 90% of the adjusted $R^2$\nneeds about 50 patients. A more complex model relating both dose and a\nbiomarker to response, with 5 to 6 parameters, needs around 100.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshrinkage <- expand.grid(\n  n     = 1:100,\n  R2app = c(0.1, 0.25, 0.5),\n  p     = c(3, 4, 5, 6)\n) |>\n  mutate(\n    S_C = 1 + (p - 2) / (n * log(1 - R2app)),        # Equation 6 of Riley et al. 2019a\n    R2app_str = paste0(\"R2app = \", R2app)\n  )\n\nggplot(shrinkage, aes(x = n, y = S_C, color = factor(p))) +\n  geom_line() +\n  ylim(0, 1) +\n  geom_hline(yintercept = 0.9, linetype = \"dashed\") +\n  labs(x = \"Number of patients\", y = \"Copas shrinkage factor\", color = \"N param.\") +\n  facet_wrap(~R2app_str)\n```\n\n::: {.cell-output-display}\n![](sizing-studies_files/figure-html/unnamed-chunk-5-1.png){width=768}\n:::\n:::\n\n\n#### Step 2: N for Apparent R² Close to Adjusted R²\n\nThe number of patients needed here also depends on $R^2$ and the parameter\ncount. For a 3-parameter Emax model with $R^2 = 0.25$, only 46 patients are\nneeded; a 5- to 6-parameter model that also describes the\nbiomarker-response relationship needs 70 to 90.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexpand.grid(R2 = c(0.1, 0.25, 0.5), p = c(3, 4, 5, 6), delta = 0.05) |>\n  mutate(n = round(1 + p * (1 - R2) / delta)) |>\n  knitr::kable(caption = \"Patients needed for apparent R² within delta of adjusted R²\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Patients needed for apparent R² within delta of adjusted R²\n\n|   R2|  p| delta|   n|\n|----:|--:|-----:|---:|\n| 0.10|  3|  0.05|  55|\n| 0.25|  3|  0.05|  46|\n| 0.50|  3|  0.05|  31|\n| 0.10|  4|  0.05|  73|\n| 0.25|  4|  0.05|  61|\n| 0.50|  4|  0.05|  41|\n| 0.10|  5|  0.05|  91|\n| 0.25|  5|  0.05|  76|\n| 0.50|  5|  0.05|  51|\n| 0.10|  6|  0.05| 109|\n| 0.25|  6|  0.05|  91|\n| 0.50|  6|  0.05|  61|\n\n\n:::\n:::\n\n\n#### Step 3: A Reasonable Estimate for the Variance\n\nThe number of patients needed to estimate the variance to within 20% or 10%\ncomes directly from the $\\chi^2$ distribution:\n\n- $70 + p$ for the variance within 20% of the true value, at 95% confidence.\n- $234 + p$ for the variance within 10% of the true value, at 95%\n  confidence.\n\n#### Step 4: A Reasonable Estimate for the Mean\n\nThe inverse $t$ distribution gives the 5th to 95th percentile confidence\ninterval directly:\n\n$$\nt\\!\\left(1 - \\frac{0.05}{2},\\; n - p - 1\\right) \\cdot \\frac{\\sigma}{\\sqrt{n}}\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexpand.grid(n = c(40, 60, 100, 200), p = c(3, 4, 5, 6)) |>\n  mutate(ci95 = signif(qt(1 - 0.05 / 2, n - p - 1) * sd_tumor / sqrt(n), 4)) |>\n  knitr::kable(caption = \"95% CI half-width on the mean, by N and parameter count\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 95% CI half-width on the mean, by N and parameter count\n\n|   n|  p|  ci95|\n|---:|--:|-----:|\n|  40|  3| 7.364|\n|  60|  3| 5.939|\n| 100|  3| 4.558|\n| 200|  3| 3.202|\n|  40|  4| 7.371|\n|  60|  4| 5.941|\n| 100|  4| 4.559|\n| 200|  4| 3.203|\n|  40|  5| 7.379|\n|  60|  5| 5.944|\n| 100|  5| 4.560|\n| 200|  5| 3.203|\n|  40|  6| 7.387|\n|  60|  6| 5.946|\n| 100|  6| 4.560|\n| 200|  6| 3.203|\n\n\n:::\n:::\n\n\nAt $\\sigma \\approx 20\\%$ in this example, this step was not the limiting\nconstraint.\n\n### Power of a Continuous Endpoint\n\nFitting only a 3-parameter Emax model, 40 to 50 patients can be enough for\nreasonable precision, given doses well distributed across the tested range.\nA 5- to 6-parameter model — say, a dose-biomarker-response model — needs 70\nto 100.\n\n## 5. Continuous and Categorical Endpoints in Oncology\n\nBecause patient numbers are limited, oncology relies especially on\nidentifying continuous safety and efficacy endpoints for initial dose\nselection. The response definition is often a mix of continuous and\ncategorical endpoints: under Response Evaluation Criteria in Solid Tumors\n(RECIST), the response classification depends on a continuous endpoint\n(percent change in tumor size) and categorical endpoints (status of\nnon-target lesions, appearance of new lesions). A new lesion's appearance is\noften the most predictive single measurement for overall survival, but as a\nbinary endpoint it is not useful for assessing dose-response in a small\nfirst-in-human study. The continuous endpoint — change in tumor size — is\nthe more practical one for identifying candidate doses; the doses it\nidentifies are then compared in larger trials.\n\n## 6. Open Questions\n\n- Riley's group publishes an R package, `pmsampsize`, not yet explored here.\n- Regression on continuous variables raises further questions about which\n  doses to test patients at.\n- The trial simulation approach in Section 2, sizing a study to a target\n  precision on the estimated dose-exposure-biomarker-response relationship,\n  is not explored in this document.\n- Is MCP-Mod (Multiple Comparison Procedure – Modeling) helpful here? It is\n  not typically used in oncology, and an oncology trial would rarely run\n  three or more expansion cohorts, which MCP-Mod usually assumes.\n",
    "supporting": [
      "sizing-studies_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}