{
  "hash": "76ae11d49661b4306b80633186602ff7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"PK-platelet modelling to select a Phase 2 dose in ITP\"\nsubtitle: \"Working specification for a B-cell depleting agent with escalation and expansion data\"\ndescription: \"Can a model of pharmacokinetic and platelet-count data for a B-cell depleting agent, fit to a small dose escalation and expansion study, select a Phase 2 dose in immune thrombocytopenia? This specifies the model, the data it needs, and the simulation study that decides whether the answer is yes.\"\ncategories: [pharmacometrics, immunology, dose selection, working document]\ndate: last-modified\ntoc: true\ntoc-depth: 3\ntoc-location: left\ntoc-expand: true\nnumber-sections: false\nhtml-math-method: mathjax\nexecute:\n  freeze: auto\n  warning: false\n  message: false\n---\n\n::: {.callout-important appearance=\"simple\"}\n**Nothing here has been fit, and six sources have been read.** The\nliterature review in [references.qmd](references.qmd) was assembled from\nsearch results and abstracts on 2026-09-09. The IWG 2009 consensus paper\nbehind Section 3, the FDA, EMA and PMDA reviews of rilzabrutinib, fostamatinib\nand efgartigimod behind Section 19, and the eltrombopag ITP model poster behind\nSections 8.3 and 8.4 were read in full and are ✅; every other source is ❌. The model in Section 8 is a candidate\nstructure written to be replaced by whatever the rituximab and thrombopoietin\nreceptor agonist papers actually report. The numbers quoted from trials are\ntranscribed from search summaries and are not safe to reuse. The\n[project index](index.qmd) lists the other documents in this folder.\n:::\n\n## In brief\n\n**The question.** A B-cell depleting agent has been given to a small number of\npatients with immune thrombocytopenia (ITP) in a dose escalation followed by\ntwo expansion arms of 20 to 40 patients each. Serum drug concentration,\ncirculating B-cell count, serum IgG and platelet count were measured serially\nin every patient. Can a model of those time courses pick the Phase 2 dose, and\nhow many patients does it save over picking from the response rate in each\narm?\n\n**The answer this specification argues for, before it is tested.** ⚠️ **Two\narms of 20 to 40 can pick the better dose without a model when the doses are\n15 or more points apart in durable response rate; at 10 points apart the model\nis what makes 20 per arm enough; the bottom of a plateau is beyond both.**\nPicking the better of two arms 15 points apart takes 20 per arm and 10 points\napart takes 40 per arm on the raw response rates alone. A model that fits the\nescalation cohorts and both expansion arms through one dose-response shape\nestimates the same contrast with 2 to 5 times the information, if the shape\nis right, which brings the 10-point case inside 20 per arm. Where adjacent\ndoses differ by 5 points, as at the bottom of a plateau, no comparison of arms\nat this size can tell them apart, and the model can name the plateau only as a\nparameter of a shape it has assumed. Section 14 computes those numbers and\nSection 15 is the simulation that checks whether the shape assumption survives\nbeing wrong. The dose selection is made on predicted platelet response, never\non the B-cell biomarker.\n\n**What the biomarker in the middle can and cannot say.** Circulating\nB cells are depleted essentially completely at every dose that gets past the\nfirst escalation cohort. Depth of depletion is therefore uninformative about\ndose, and the quantity that still varies with dose is the **duration** of\ndepletion, measured as time to repopulation. Section 7 is that argument and it\nis the reason the model in Section 8 is written around a duration. Duration of\ndepletion carries dose into the model; it does not choose the dose, because\ncomplete and durable depletion of circulating B cells is not the same thing as\nmaximal platelet response, and the selection rule in Section 13 is written on\nthe platelet endpoint for that reason.\n\n**The chain the model has to cross.**\n\n```{mermaid}\nflowchart LR\n    D[\"Dose\"] --> C[\"Concentration\"]\n    C --> B[\"Circulating B cells<br/>saturates on depth\"]\n    C --> T[\"Tissue B cells<br/>spleen, marrow\"]\n    B --> PB[\"Plasmablasts\"]\n    T --> PB\n    PB --> A[\"Anti-platelet IgG<br/>not measured\"]\n    LLPC[\"Long-lived plasma cells<br/>not depleted\"] --> A\n    A --> K[\"Platelet destruction rate\"]\n    K --> P[\"Platelet count\"]\n```\n\nTwo states in that chain are unobserved in any realistic dataset: tissue B\ncells and anti-platelet immunoglobulin G (IgG). Both sit between the drug and\nthe endpoint. The model collapses them into one transduction delay whose prior\ncomes from published time-to-response in rituximab-treated ITP, and estimates\nonly the dose-dependent part.\n\n**How the question gets answered.** By simulation, in Section 15. Generate\nescalation and expansion datasets from an assumed true model at a realistic\nsample size, fit the candidate model, apply the dose selection rule in Section\n13, and count how often the selected dose is the true best dose. The\ndeliverable is that operating characteristic, per sample size and per dosing\nscheme, not a dose recommendation for any real compound.\n\n**Out of scope, stated once.**\n\n- ❌ **A recommendation for any named drug.** The compound in this\n  specification is generic. Ianalumab, rituximab and mezagitamab appear as\n  sources of realistic parameter values and as external checks, and nothing\n  here is a dosing statement about any of them.\n- ❌ **A safety model.** Dose-limiting toxicity, infection risk and\n  hypogammaglobulinaemia do not enter. The selection rule in Section 13 assumes\n  a safe dose range has already been established and chooses inside it.\n- ❌ **A mechanistic B-cell systems model.** No germinal centres, no B-cell\n  receptor signalling, no compartment-by-compartment trafficking. Published\n  quantitative systems pharmacology models of B-cell differentiation exist and\n  are listed in the references; they are a source of structure, not something\n  to be rebuilt at this sample size.\n- ❌ **Bleeding.** Every IWG response definition carries a bleeding clause\n  (Section 3.1) and this project models platelet count only, so its predicted\n  response rates are upper bounds.\n- ❌ **Patient-level reanalysis of any published trial.** No such data is\n  available here. Public aggregate results are used only as external checks.\n\n------------------------------------------------------------------------\n\n## 1. Objective\n\nDetermine whether a joint model of drug concentration, circulating B-cell\ncount and platelet count, fit to a Phase 1 dose escalation plus expansion\nstudy in primary ITP, supports a Phase 2 dose selection that a later\nrandomized dose comparison would confirm.\n\nThe setting assumed throughout:\n\n- a monoclonal antibody or antibody-like agent whose mechanism is B-cell\n  depletion, given intravenously or subcutaneously as a short course of two to\n  four administrations;\n- an escalation of three to five dose levels, three to six patients per level,\n  whose data are kept and fit alongside the expansion;\n- expansion in two arms at doses chosen from the escalation, twenty to forty\n  patients per arm, so that the whole study is fifty to one hundred patients;\n- serial pharmacokinetic (PK) sampling, circulating B-cell counts by flow\n  cytometry, serum total immunoglobulin G (IgG), and platelet counts at every\n  visit for six to twelve months; anti-platelet IgG where an assay is run;\n- primary clinical endpoint a durable platelet response, defined as platelet\n  count $\\ge 50 \\times 10^9$/L sustained over a specified fraction of the\n  observation window without rescue therapy.\n\n## 2. Uncertainties, ranked\n\nRanked by how much each would change the answer, with where the document\ndeals with it. The first is the one that could make the whole approach\nwrong, and nothing in the study measures it.\n\n1. **Tissue depletion is not measured, and tissue is where the disease is.**\n   The autoreactive plasmablasts and plasma cells that make anti-platelet IgG\n   sit in the spleen and the bone marrow. No ITP trial biopsies either, and\n   a peripheral B-cell count says how well the drug clears blood, not tissue.\n   Ianalumab's own Phase 2b dose selection in Sjögren's needed a hypothesized\n   tissue receptor-occupancy model precisely because the circulating count\n   could not stand in for it (references, entry 2). The specification's\n   response to this is a set of proxies (Section 4: circulating plasmablasts,\n   BAFF, the IgG trajectory, the autoantibody titre where measured), a\n   structural term for the fraction of autoantibody production the drug\n   cannot reach (Section 8.3, $\\phi_i$), and a wrong-structure case in the\n   simulation where tissue depletion lags peripheral depletion (Section 15).\n   If the wrong-structure case fails, the answer to the project is no, and\n   Section 17 says so first.\n2. **The response is a mixture, and the non-responder fraction may depend on\n   dose or may not.** Rituximab's 60% initial and 20 to 30% five-year\n   response rates put the long-lived plasma-cell floor at roughly half the\n   patients. Whether a higher dose or longer depletion lowers that floor is\n   the dose-response the study is trying to see, and it is not known.\n   Sections 8.4 and 12.\n3. **The transduction delay is long and wide.** Rituximab reaches peak\n   platelet response 14 to 180 days after dosing (Section 3.5). A thirteen-fold\n   spread across patients means a slow responder and a non-responder look the\n   same for months, and the prior on $k_{e0}$ is doing real work. Section 10.\n4. **The dose-response shape that lets the model pool arms is assumed.** The\n   factor of 2 to 5 in Section 14 comes from a two-parameter logistic in\n   log dose; a plateau shape pools less and a wrong shape pools confidently\n   wrong. Section 15's simulation is the check.\n5. **The duration signal per patient is weak.** One PK half-life of extra\n   depletion per doubling of dose, against a between-patient spread in\n   recovery rate of 22 to 126% CV in published models. Section 6.2.\n6. **Concomitant therapy may dominate the platelet trajectory.** Most patients\n   entering the study are on a TPO receptor agonist or corticosteroids or\n   both, and rescue therapy is informative censoring. Sections 9 and 12.\n7. **The anti-platelet antibody assay is positive in only about half of\n   patients and is semi-quantitative.** Where negative, the autoantibody\n   layer stays latent. Sections 4 and 8.5.\n8. **Bleeding is in every response definition and not in the model.**\n   Predicted response rates are upper bounds. Section 3.1.\n9. **The endpoint itself varies by trial** in threshold, durability window\n   and rescue rules (Section 3.4), so a response rate is not one number\n   across programmes and the external checks in Section 16 compare shapes\n   rather than rates.\n\n## 3. Endpoints in ITP\n\nThe standard definitions come from the International Working Group (IWG)\nconsensus, Rodeghiero et al., *Blood* 2009;113:2386-2393. That paper has been\nread, and the definitions in this section are quoted from it rather than from\na summary of it, so they are the only ✅ entries in\n[references.qmd](references.qmd).\n\n**There is no partial response in ITP.** The IWG panel considered \"partial\"\nand \"minimal\" response, which appear widely in the older literature, and\ndeliberately dropped both, \"because of the wide heterogeneity in the criteria\nused in these definitions.\" What replaced them is a two-level scale: complete\nresponse and response. A trial reporting a PR in ITP is using a\nnon-standard definition and has to say what it is.\n\n### 3.1 The IWG response criteria\n\n| Term | Definition |\n|:---|:---|\n| **CR**, complete response | Platelet count $\\ge 100 \\times 10^9$/L **and** absence of bleeding |\n| **R**, response | Platelet count $\\ge 30 \\times 10^9$/L **and** at least a 2-fold increase over the baseline count **and** absence of bleeding |\n| **NR**, no response | Platelet count $< 30 \\times 10^9$/L **or** less than a 2-fold increase over baseline **or** bleeding |\n| **Loss of CR** | Platelet count below $100 \\times 10^9$/L **or** bleeding |\n| **Loss of R** | Platelet count below $30 \\times 10^9$/L **or** less than a 2-fold increase over baseline **or** bleeding |\n| **Time to response** | Time from starting treatment to achievement of CR or R |\n| **Duration of response** | From achievement of CR or R to loss of CR or R; also reported as the proportion of cumulative time spent in CR or R over the period examined |\n| **Corticosteroid dependence** | Ongoing or repeated corticosteroids for at least 2 months to hold platelets at or above $30 \\times 10^9$/L or to avoid bleeding. Corticosteroid-dependent patients count as non-responders |\n\n: IWG 2009 response criteria, Table 2 of Rodeghiero et al. ✅ {tbl-colwidths=\"[24,76]\"}\n\nThree qualifications from the same table, each of which changes what a model\nhas to simulate.\n\n**A response is a confirmed response.** Platelet counts must be confirmed on\nat least two separate occasions, at least 7 days apart when used to define CR\nor R, and 1 day apart when used to define NR or loss of response. A single\ncount above threshold is not an event, which is why Section 15 simulates the\nvisit schedule rather than the underlying trajectory.\n\n**Bleeding is part of every definition.** CR, R and NR each carry a bleeding\nclause. A model of platelet count alone predicts a necessary condition for\nresponse, not response. The specification treats bleeding as out of scope and\nthis is where that costs something: predicted response rates from Section 13\nare upper bounds.\n\n**Baseline is the count at the start of the investigated treatment.** The\n2-fold increase in the definition of R is relative to that count, so baseline\nseverity enters the endpoint itself and not only the model. This is the second\nargument for requirement 6 in Section 9.\n\n### 3.2 Disease phases and severity\n\n| Term | Definition |\n|:---|:---|\n| **Primary ITP** | Isolated thrombocytopenia, platelet count $< 100 \\times 10^9$/L, with no other cause |\n| **Newly diagnosed** | Within 3 months of diagnosis |\n| **Persistent** | Between 3 and 12 months from diagnosis |\n| **Chronic** | Lasting more than 12 months |\n| **Severe** | Bleeding at presentation sufficient to mandate treatment, or new bleeding requiring a different platelet-enhancing agent or an increased dose |\n| **Refractory** | Failure to achieve at least R, or loss of R, after splenectomy, plus a need for treatment to minimize bleeding risk |\n\n: IWG 2009 disease phases, Tables 1 and 4 ✅ {tbl-colwidths=\"[24,76]\"}\n\nThe phase decides the trial population and therefore the response rate the\nmodel has to reproduce. Persistent and chronic ITP is where every agent in\nSection 16's external checks was studied, and spontaneous remission is common\nenough in newly diagnosed ITP that a placebo arm there behaves differently.\n\n### 3.3 Primary and secondary endpoints as the IWG specifies them for trials\n\nTable 5 of the same paper gives trial-adapted criteria.\n\n- **Primary endpoint: CR or R based on platelet count, as in Section 3.1.**\n- **Secondary endpoints:** adverse events; need for rescue interventions;\n  corticosteroid and concomitant treatment reduction; rate of splenectomy;\n  bleeding measured on a validated scale; health-related quality of life on a\n  validated instrument; and pharmacoeconomic analysis where possible. The\n  paper notes that any of these may become the primary endpoint depending on\n  the trial design.\n- **Eligibility:** entry platelet count below $30 \\times 10^9$/L, or below\n  $50 \\times 10^9$/L in specific settings, on steroids, or with bleeding.\n- **A predefined exceedingly high platelet count induced by treatment may be\n  recorded as an adverse event.** A model whose drug effect is unbounded\n  above has to simulate that too.\n\n### 3.4 What recent trials actually use\n\nTrials have drifted away from the IWG thresholds, toward $50 \\times 10^9$/L\nwith a durability requirement. Every definition below is transcribed from a\nsearch summary and carries ❌ in the references.\n\n| Trial, drug | Primary endpoint as reported |\n|:---|:---|\n| LUNA3, rilzabrutinib | Platelet $\\ge 50 \\times 10^9$/L for $\\ge$ two-thirds of $\\ge 8$ of the last 12 of 24 weeks, no rescue |\n| ADVANCE IV, efgartigimod | Platelet $\\ge 50 \\times 10^9$/L for at least 4 of the last 6 weeks |\n| VAYHIT2, ianalumab | Time to treatment failure |\n| Orelabrutinib phase 2 | Two consecutive platelet counts $\\ge 50 \\times 10^9$/L within 4 weeks, no rescue |\n| Rilzabrutinib phase 1/2 part A | Two consecutive counts $\\ge 50 \\times 10^9$/L and an increase $\\ge 20 \\times 10^9$/L over baseline, no rescue |\n\n: Endpoint definitions in recent ITP trials ❌ {tbl-colwidths=\"[32,68]\"}\n\nTwo consequences for this project. The threshold the model has to simulate is\n50, not the IWG's 30 or 100, and the durability window differs by trial, so\nSection 15's simulated endpoint is a parameter of the simulation rather than a\nconstant. And VAYHIT2's time-to-treatment-failure endpoint is a different\nmathematical object from a durable response proportion, which is why Section\n16's first external check compares a predicted plateau rather than a predicted\nrate.\n\n### 3.5 Time to response by agent, and where the transduction prior comes from\n\nTable 3 of the IWG paper reports, per agent, the time to initial response and\nthe time to peak response over the reported dose range. It is the published\nprior on the transduction delay $k_{e0}$ in Section 8.4, and unlike everything\nelse feeding that prior it has been read.\n\n| Agent | Reported dose range | Time to initial response | Time to peak response |\n|:---|:---|:---|:---|\n| IVIg | 0.4-1 g/kg per dose, 1-5 doses | 1-3 d | 2-7 d |\n| Anti-D | 75 µg/kg iv | 1-3 d | 3-7 d |\n| Prednisone | 1-4 mg/kg po daily, 1-4 wk | 4-14 d | 7-28 d |\n| Romiplostim (AMG531) | 3-10 µg/kg weekly sc | 5-14 d | 14-60 d |\n| Eltrombopag | 25-75 mg po daily | 7-28 d | 14-90 d |\n| **Rituximab** | **375 mg/m² per dose, 4 weekly doses** | **7-56 d** | **14-180 d** |\n\n: IWG 2009 Table 3, selected rows ✅ {tbl-colwidths=\"[22,32,23,23]\"}\n\nThe rituximab row is the one this project needs, and its width is the point.\nTime to peak response spans 14 to 180 days, which is a factor of thirteen. A\ntransduction delay with that much spread across patients is why Section 10\ngives up on estimating $k_{e0}$ and $\\eta_i$ jointly, and why requirement 4 in\nSection 9 asks for follow-up past the point where a slow response would have\ncompleted. The contrast with the two rows above it is also the argument of\nSection 19: a thrombopoietin receptor agonist reaches peak effect in weeks\nthrough a mechanism that acts directly on platelet production, and that is the\nclass whose PK-platelet models are published.\n\n## 4. Biomarkers\n\nWhat can be measured in blood on this study, what each one reports on, and\nwhat the model does with it. The tissue compartment of uncertainty 1 has no\ndirect measurement; the last three rows are its proxies. Everything in this\nsection outside pharmacometrics is from general knowledge and carries ❌ in\nthe references (entry 30) until sourced.\n\n| Biomarker | What it reports | Role in the model | Section |\n|:---|:---|:---|:---|\n| **Platelet count** | The endpoint. Destruction and production together | The response variable | 3, 12 |\n| **Immature platelet fraction (IPF)** | Share of circulating platelets with residual RNA; high when the marrow is compensating for destruction | Separates a fall in $k_{\\rm dest}$ from a rise in production; one extra number on a routine count | 9, 8.3 |\n| **Serum thrombopoietin (TPO)** | Inversely related to megakaryocyte and platelet mass; normal or low in ITP, high in marrow failure | Diagnostic context; a covariate on baseline production if it varies | — |\n| **Glycocalicin** | Soluble fragment of platelet GPIb shed on destruction | A direct destruction-rate marker; rarely measured in trials | — |\n| **CD19+ or CD20+ B cells** | Circulating B-cell count; below the flow limit at every therapeutic dose | The layer that carries dose into the model, through time to repopulation | 6.2, 8.2 |\n| **B-cell subsets**: naive, memory (CD27+), plasmablasts (CD27hi CD38hi) | Which compartment is repopulating, and whether plasmablasts, the immediate precursors of antibody-secreting cells, are still being generated | The circulating plasmablast count is the closest blood proxy for the tissue compartment | 2, 8.5 |\n| **Serum total IgG, IgM, IgA** | Bulk antibody, maintained mostly by long-lived plasma cells the drug does not deplete | Covariate identifying the plasma-cell floor $\\phi_i$; the whole mechanism for an FcRn blocker | 8.5 |\n| **BAFF** | B-cell survival factor; rises when B cells are depleted and falls as they return | A feedback marker of depletion depth in tissue as well as blood; the target of ianalumab | 8.5 |\n| **Anti-platelet IgG** by MAIPA, against GPIIb/IIIa, GPIb/IX, GPIa/IIa | The autoantibody itself, by glycoprotein target. Direct assay on the patient's platelets is more sensitive than indirect on serum. Positive in roughly half to 60% of ITP | $A(t)$ observed rather than latent, where positive and serial | 8.3, 8.5 |\n| **Anti-GPIb/IX specificity** | Antibodies to GPIb/IX clear platelets by desialylation and hepatic uptake, Fc-independently, and predict poorer response to IVIg and corticosteroids | A response covariate, and a mechanism that FcγR-blocking drugs would miss | 12 |\n| **Platelet-associated IgG (PAIgG)** | Total IgG on platelets; elevated in thrombocytopenia of any cause | Not useful; listed so that it is not mistaken for the row above | — |\n\n: Blood biomarkers in ITP and what the model does with each {tbl-colwidths=\"[24,32,32,12]\"}\n\n**Autoantibodies that can be measured in circulation.** The answer to\nwhether a known autoreactive antibody is measurable is yes, with the\nqualifications in the MAIPA row: the antibodies are against platelet\nglycoproteins, GPIIb/IIIa most often, then GPIb/IX, and a minority against\nGPIa/IIa or GPV; the assay names the target; and it is negative in a large\nminority of patients with a clinical diagnosis of ITP, either because the\ntitre is low or because the antibody is against something the panel does not\ncarry. A serial MAIPA in the patients who are positive at baseline is the one\naddition to a standard protocol that would let the model see the autoantibody\nfall before the platelet count rises (Section 8.5).\n\n## 5. The drugs this document refers to\n\nEvery drug named anywhere in this folder, by mechanism, with what it does in\nITP and where it stands. The compound the specification is written for is\ngeneric; these are the sources of its parameters and its external checks.\nFirst-line therapy, corticosteroids, intravenous immunoglobulin (IVIg) and\nanti-D, is context only. The last column says whether the status and the\nresponse figure were checked against a source; most were not.\n\n| Drug | Target and mechanism | Status in ITP, and line | Response as reported | |\n|:---|:---|:---|:---|:--|\n| **Deplete B cells** | | | | |\n| Rituximab | Chimeric anti-CD20 IgG1; complement- and antibody-dependent lysis of CD20+ B cells | Off-label second line, 375 mg/m² or 100 mg weekly × 4 | About 60% initial, 20 to 30% at five years | ❌ |\n| Ianalumab | Afucosylated anti-BAFF-R IgG1; ADCC-enhanced depletion plus BAFF-R signalling blockade | Phase 3 complete (VAYHIT2, with eltrombopag after first line; VAYHIT1 later line); not approved at time of writing; 4 monthly doses | 12-month freedom from treatment failure 54% at 9 mg/kg, 51% at 3 mg/kg, 30% placebo | ❌ |\n| Obinutuzumab, obexelimab, telitacicept, povetacicept | Anti-CD20; anti-CD19/FcγRIIb; TACI-Fc; APRIL/BAFF inhibitor | Searched, nothing in ITP found | None | ❌ |\n| **Deplete plasma cells** | | | | |\n| Mezagitamab | Anti-CD38 IgG1, subcutaneous; depletes plasmablasts and plasma cells | Phase 2b positive, Phase 3 ongoing, chronic ITP | 10 of 11 responders at 600 mg weekly × 8, 3 of 13 on placebo | ❌ |\n| **Remove the autoantibody** | | | | |\n| Efgartigimod | FcRn-blocking IgG1 Fc fragment; accelerates IgG catabolism | Approved in Japan 2024, IV, primary ITP; ADVANCE NEXT running for FDA | Sustained response 25.6% against 6.7% placebo, ADVANCE IV | ✅ |\n| Rozanolixizumab | Anti-FcRn IgG4, subcutaneous | Phase 2 in ITP; ITP programme not continued | Platelets $\\ge 50$ at least once in 36 to 67% by arm | ❌ |\n| IVIg | Pooled IgG; FcRn competition and FcγR blockade | First line and rescue | The rodent-model drug of entries 28 and 29 | ❌ |\n| **Block the destruction step** | | | | |\n| Fostamatinib | SYK inhibitor prodrug (active moiety R406); blocks FcγR-mediated phagocytosis | FDA 2018, EMA 2020; chronic ITP after insufficient response to a prior therapy; 100 mg BID titrated to 150 | Stable response 18% across two Phase 3 studies | ✅ |\n| Rilzabrutinib | Reversible covalent BTK inhibitor; less autoantibody production and less FcγR phagocytosis | FDA August 2025; persistent or chronic ITP after insufficient response; 400 mg BID | Durable response 23% against 0% placebo, LUNA 3 | ✅ |\n| Orelabrutinib | BTK inhibitor, once daily | Phase 2 in China, Phase 3 ongoing | 40% at 50 mg, 22% at 30 mg, 33 patients | ❌ |\n| **Raise platelet production** | | | | |\n| Romiplostim | TPO receptor agonist peptibody, subcutaneous weekly | FDA 2008; ITP after insufficient response to corticosteroids, immunoglobulins or splenectomy; titrated 1 to 10 µg/kg | Response in most patients while dosed; loses response on stopping | ❌ |\n| Eltrombopag | Oral small-molecule TPO receptor agonist | FDA 2008; same line; 25 to 75 mg daily titrated | Same pattern; the 155-patient model is entry 26 | ❌ |\n| Avatrombopag | Oral TPO receptor agonist | FDA 2019 for chronic ITP | Same pattern | ❌ |\n| Lusutrombopag | Oral TPO receptor agonist | Not an ITP drug; approved for procedures in liver disease | Source of a model only | ❌ |\n\n: Drugs named in this project, by mechanism {tbl-colwidths=\"[14,26,30,26,4]\"}\n\nThe four mechanism groups are the four rows of the chain in the In brief\ndiagram, read from the drug end. Depleting B cells or plasma cells acts on\nautoantibody production; removing the autoantibody acts on its concentration;\nblocking the destruction step acts on what the autoantibody does; and raising\nproduction bypasses the chain. The published PK-platelet models are all in the\nlast group, and Section 19 is about why.\n\n## 6. The question in four parts\n\n\"Can the model select the dose\" is not answerable as written. It becomes\nanswerable when split into four, each of which the simulation in Section 15\nreports separately.\n\n**6.1 Is dose to exposure identifiable?** Yes, and it is not the problem. A\ntwo-compartment model with linear clearance fits from the escalation PK\nalone.\n\n**6.2 Is exposure to B-cell depletion identifiable?** The slope is; the\n$EC_{50}$ is not, at this study's size, and the published B-cell depletion\nmodels say why. Every one found uses an indirect-response structure with the\ndrug raising the B-cell loss rate, and three report what happened to\n$EC_{50}$ (references, entries 31 to 33):\n\n- ofatumumab, 1,486 patients over doses from 3 mg to 700 mg, two low-dose\n  arms giving partial depletion: $EC_{50}$ estimated at 8.5% RSE;\n- rituximab, 63 paediatric patients at full dose: $E_{\\max}$ and $ED_{50}$\n  both estimated, $ED_{50}$ at 61% RSE with a 13-fold confidence interval,\n  and the authors attribute the imprecision to \"the highly efficacious\n  doses\";\n- inebilizumab, 213 subjects over a 100-fold dose range: the $E_{\\max}$\n  model was abandoned because the estimated $EC_{50}$ fell below the PK\n  assay's limit of quantification, and a log-linear slope replaced it.\n\nThe arithmetic behind all three. With loss rate $k_{\\rm out}(1 + E)$ and\n$E = E_{\\max} C / (EC_{50} + C)$, the nadir is $B_0 / (1 + E)$. Both\n$E_{\\max}$ estimates are about 155 to 160, so at $C = EC_{50}$ the nadir is\nalready about 1% of baseline, below the flow-cytometry limit. Half-maximal\n*depletion* happens near $C = EC_{50} / E_{\\max}$, two orders of magnitude\nbelow $EC_{50}$. The whole band of concentrations over which the cell count\nis informative therefore sits between $EC_{50}/E_{\\max}$ and $EC_{50}$, far\nbelow therapeutic exposure and often below the PK assay. Above that band the\ndepth is censored; repopulation begins when the concentration falls back\nthrough it, and its timing identifies $E_{\\max}/EC_{50}$ as one slope.\n$E_{\\max}$ and $EC_{50}$ separate only if some cohort sits inside the band\nwith a quantifiable nadir and quantifiable PK. Ofatumumab had both, from its\n3 mg and 10 mg arms; inebilizumab, with a wider dose range, had neither.\n\nSo the proportional model is the identifiable one, and not by convention. The\nspecification parameterizes Section 8.2 as a log-linear slope on the loss\nrate and keeps $E_{\\max}$ as an alternative to test only if the lowest\nescalation cohort shows a quantifiable nadir. The slope is what the time to\nrepopulation depends on, so nothing downstream loses anything.\n\n**What the duration signal carries.** With linear PK in the tail,\neach doubling of dose adds one PK half-life to the time the concentration\nspends above the transition band: about 10 days for ianalumab, 15 to 20 for\nrituximab. Between-patient variability in the recovery rate was 126% CV in the\ninebilizumab model and 22% CV in the paediatric rituximab CD19 half-life. At\nthree to six patients per level the dose signal in $T_{\\rm rep}$ is one\nhalf-life per doubling against that spread, which is why Section 9 asks for\nthe escalation to span at least eight-fold and for B cells monthly through\nrepopulation, and why Section 10 profiles the slope rather than assuming it.\nThe duration is an input to the model and not a selection criterion; see the\nlast paragraph of the In brief.\n\n**6.3 Is B-cell depletion to platelet response identifiable?** This is the\nquestion. The link is indirect, delayed by weeks, and mediated by two\nunmeasured states. Section 10 sets out what has to be assumed for it to be\nidentifiable at all. The FDA review of rilzabrutinib (references, entry 22) is\nan existence proof one step short: a longitudinal platelet model for a drug\nthat blocks destruction fit adequately at 305 patients pooled across two\ntrials at one dose. Whether it does at 40 patients across four doses is what\nSection 15 tests.\n\n**6.4 Does a wrong answer cost anything?** The selection rule in Section 13 is\nscored against a loss function, not against a point estimate. Selecting a dose\none level above the true plateau bottom costs exposure and drug supply;\nselecting one level below costs the Phase 2 result. Those are not\nsymmetric and the rule reflects that.\n\n## 7. Why depth of B-cell depletion carries no dose information\n\nPeripheral B-cell counts fall below the limit of quantification within days at\nevery dose that any B-cell depleting agent is developed at. The evidence in\nthe references, all unverified:\n\n- rituximab at 100 mg weekly for four weeks produces a pooled overall platelet\n  response rate close to the rate at 375 mg/m² weekly for four weeks, a\n  roughly four-fold difference in dose, and complete peripheral depletion at\n  both;\n- ianalumab produces \"rapid and profound\" peripheral depletion across the\n  doses studied in primary Sjögren's syndrome, which is why its Phase 2b dose\n  selection used tissue receptor occupancy rather than circulating B cells as\n  the second biomarker;\n- in ITP specifically, ianalumab at 3 mg/kg and 9 mg/kg gave 12-month\n  freedom-from-treatment-failure probabilities within a few percentage points\n  of each other in the Phase 3 VAYHIT2 trial, over a three-fold dose range.\n\nThree consequences follow for the model.\n\n**Duration replaces depth.** The dose-dependent quantity is the time from the\nlast administration until circulating B cells return to a defined fraction of\nbaseline. Call it $T_{\\rm rep}$. It is a derived quantity of the model in\nSection 8.2, it is directly observable in the escalation data, and it is\nmonotone in dose across a range where depth is flat. It is also a weak signal\nper patient, one PK half-life per doubling of dose against a between-patient\nspread in recovery rate that published models put at 22 to 126% CV (Section\n6.2), so it is read across the whole escalation and not from any one cohort.\n\n**The plateau boundary is the target of estimation.** The selection question\nis where the dose-response curve stops rising. A model built to\nestimate a slope will be asked for a number the data cannot give; a model\nbuilt to locate a plateau boundary is being asked something the escalation\ncohorts can answer.\n\n**Tissue depletion carries the dose-response the platelet endpoint depends\non, and it is not measured.** Autoreactive plasmablasts in ITP disseminate to spleen and\nbone marrow. Peripheral clearance says nothing about tissue clearance, and no\nPhase 1 study biopsies spleen. This is the largest source of structural\nuncertainty in the specification, and Section 17 treats it as the main\nroute to a negative answer.\n\n## 8. The model\n\nFour layers, written top to bottom in the order the drug traverses them. Each\ncarries a note on whether its parameters are estimated here, fixed from the\nliterature, or collapsed away.\n\n### 8.0 State variables and parameters of the pharmacodynamic model\n\nThe PK layer is standard and not tabulated. Everything downstream of it is,\nso that the equations in 8.2 to 8.4 can be read against one list. \"Full\"\nmeans Sections 8.2 and 8.3; \"reduced\" means Section 8.4, the model that gets\nfit.\n\n| Symbol | What it is | Units | Full or reduced | How it is set |\n|:---|:---|:---|:---|:---|\n| **States** | | | | |\n| $B(t)$ | Circulating B-cell count | cells/µL | Both | Observed |\n| $B_{\\rm tissue}(t)$ | B cells in spleen and marrow | relative to baseline | Full | Unobserved; proxies in Section 4 |\n| $A(t)$ | Anti-platelet IgG | relative to $A_{50}$ | Full | Latent, or observed where MAIPA is serial |\n| $P_1, P_2, P_3$ | Platelet precursors in the maturation chain | cells/µL-equivalent | Both | Unobserved |\n| $P(t)$ | Circulating platelet count | $10^9$/L | Both | Observed; the endpoint |\n| $u(t) = 1 - B/B_0$ | Depletion signal | none, 0 to 1 | Reduced | Derived from $B$ |\n| $Z(t)$ | Transduced depletion signal, $u$ after a lag | none, 0 to 1 | Reduced | Derived |\n| **B-cell layer** | | | | |\n| $B_0$ | Baseline B-cell count, $= k_{\\rm in}/k_{\\rm out}$ | cells/µL | Both | Estimated per patient |\n| $k_{\\rm in}$ | B-cell production rate | cells/µL/day | Both | Estimated |\n| $k_{\\rm out}$ | B-cell loss rate; sets repopulation speed | 1/day | Both | Estimated; published 0.0124/day (ofatumumab), half-life 173 d (rituximab) |\n| $S$ | Drug effect slope on $k_{\\rm out}$ per log concentration | none | Both | Estimated |\n| $C_{\\rm ref}$ | Concentration scale for $S$ | mg/L | Both | Fixed at PK LLOQ |\n| $E_{\\max}, EC_{50}$ | Alternative saturable drug effect | none, mg/L | Both | Fit only if a cohort has a quantifiable nadir (Section 6.2) |\n| $\\alpha$ | Repopulation threshold defining $T_{\\rm rep}$ | none | Both | Fixed, 0.2 |\n| **Autoantibody layer** | | | | |\n| $k_{\\rm syn}$ | Autoantibody production rate at baseline | 1/day | Full | Fixed; scale absorbed into $A_{50}$ |\n| $k_{\\rm deg}$ | IgG elimination rate | 1/day | Full | Fixed, half-life about 21 d |\n| $\\phi_i$ | Fraction of autoantibody production from long-lived plasma cells the drug does not deplete | none, 0 to 1 | Full | Random effect; the non-responder fraction |\n| $A_{50}$ | Autoantibody level doubling the destruction rate | same as $A$ | Full | Fixed; scale |\n| **Platelet layer** | | | | |\n| $k_{\\rm prod}$ | Precursor production rate | cells/day | Both | Fixed from TPO-RA models |\n| $k_{\\rm tr}$ | Maturation transit rate | 1/day | Both | Fixed from TPO-RA models |\n| $k_{\\rm dest,0}$ | Physiological platelet loss rate | 1/day | Both | Fixed from 7 to 10 d lifespan |\n| $k_{\\rm dest}(t)$ | Actual platelet loss rate under disease and drug | 1/day | Both | Derived: from $A(t)$ in 8.3, from $Z(t)$ in 8.4 |\n| **Reduced-model link** | | | | |\n| $k_{e0}$ | Transduction rate from $u$ to $Z$ | 1/day | Reduced | Informative prior from rituximab time to response |\n| $\\theta_i$ | Untreated excess destruction, as a multiple of $k_{\\rm dest,0}$ | none | Reduced | Estimated per patient from pre-treatment counts |\n| $\\eta_i$ | Fraction of $\\theta_i$ the drug can remove; $\\approx 1 - \\phi_i$ | none, 0 to 1 | Reduced | Random effect with a mixture; the responder indicator |\n\n: Pharmacodynamic states and parameters {tbl-colwidths=\"[13,33,14,12,28]\"}\n\n### 8.1 Pharmacokinetics\n\nTwo compartments with linear clearance. Writing $C$ for concentration in the\ncentral compartment and $C_p$ in the peripheral,\n\n$$\nV_c \\frac{dC}{dt} = -CL \\cdot C - Q(C - C_p) + \\text{input}, \\qquad\nV_p \\frac{dC_p}{dt} = Q(C - C_p)\n$$\n\nNo target-mediated term. B-cell-mediated elimination is real for anti-CD20\nantibodies and the published models carry it (references, entries 32 and 34),\nbut at this study's size it is not estimable and it is not the question.\nWhere a patient's baseline B-cell count shifts clearance, it enters as a\ncovariate on $CL$, which is also how Section 11 handles the confounding it\ncauses. **Estimated here**, with informative priors on $CL$ and $V_c$ from\ntypical immunoglobulin G1 values.\n\n### 8.2 Circulating B cells\n\nAn indirect response model on the loss rate, with the drug effect written as\na log-linear slope, which is the form the published models converge on when\ndepletion is complete at every studied dose (Section 6.2):\n\n$$\n\\frac{dB}{dt} = k_{\\rm in} - k_{\\rm out}\\left(1 + S \\cdot \\log(1 + C/C_{\\rm ref})\\right) B\n$$\n\nwith $C_{\\rm ref}$ fixed at the PK assay's limit of quantification so that\n$S$ is in units the data can see. The $E_{\\max}$ form,\n$E = E_{\\max} C/(EC_{50} + C)$, is the alternative to fit only if the lowest\nescalation cohort has a nadir above the flow-cytometry limit; when it does not,\n$E_{\\max}$ and $EC_{50}$ are identified only as their ratio and the slope form\nis the same model with one fewer parameter.\n\nwith $B(0) = B_0 = k_{\\rm in}/k_{\\rm out}$. The quantity carried forward is\n\n$$\nT_{\\rm rep} = \\inf\\{\\,t > t_{\\rm last} : B(t) \\ge \\alpha B_0\\,\\}, \\qquad \\alpha = 0.2\n$$\n\nthe time from the last dose until circulating B cells recover to 20% of\nbaseline. $\\alpha$ is a property of the definition, not of a dataset, and it\nis fixed at 0.2 so that $T_{\\rm rep}$ is measurable above the flow cytometry\nquantification limit in most patients.\n\n**Estimated here** with the caveat of Section 6.2: $S$ is estimated, and\n$k_{\\rm out}$ — which sets the repopulation rate and therefore\n$T_{\\rm rep}$ — is the parameter the escalation data informs best. Published\nvalues to compare against: $k_{\\rm out}$ 0.0124 per day for ofatumumab, a\nCD19 half-life of 173 days for paediatric rituximab, a B-cell lifespan of 391\ndays for inebilizumab (references, entries 31 to 33).\n\n### 8.3 Autoantibody and platelet dynamics\n\nThe published platelet-side structure comes from the thrombopoietin receptor\nagonist (TPO-RA) literature, where a four-compartment lifespan model is\nstandard: one precursor production compartment, two transit compartments for\nmaturation, and one circulating platelet compartment. Written with $P_1, P_2,\nP_3$ for the maturation chain and $P$ for circulating platelets,\n\n$$\n\\frac{dP_1}{dt} = k_{\\rm prod} - k_{\\rm tr} P_1, \\qquad\n\\frac{dP_i}{dt} = k_{\\rm tr}(P_{i-1} - P_i), \\qquad\n\\frac{dP}{dt} = k_{\\rm tr} P_3 - k_{\\rm dest}(t)\\, P\n$$\n\nITP enters through the destruction rate, which anti-platelet IgG $A(t)$\nelevates above its physiological value. $A(t)$ is latent unless an\nanti-platelet antibody assay was run, and Section 8.5 says what changes when\nit was:\n\n$$\nk_{\\rm dest}(t) = k_{\\rm dest,0}\\left(1 + \\frac{A(t)}{A_{50}}\\right), \\qquad\n\\frac{dA}{dt} = k_{\\rm syn}\\, g(B_{\\rm tissue}) - k_{\\rm deg} A\n$$\n\n**Fixed from the literature, not estimated.** $k_{\\rm tr}$ and $k_{\\rm\ndest,0}$ come from the TPO-RA models and from the 7 to 10 day physiological\nplatelet lifespan. The eltrombopag ITP model (references, entry 26) made the\nsame decision for the same reason: its authors could not estimate the\nproduction rate and the transit rate from 155 ITP patients and fixed both to\nhealthy-volunteer values, 1.43 Gi/L·h and 0.0253 h⁻¹. $k_{\\rm deg}$ is the IgG elimination rate, roughly a\nthree-week half-life. Nothing in an ITP dataset without a TPO-RA arm perturbs\nplatelet production enough to identify the maturation chain independently.\n\nThe reason ITP responses to B-cell depletion take four to eight weeks, and the\nreason a substantial minority never respond at all, both live in the $A$\nequation. Long-lived plasma cells carry neither CD20 nor the B-cell activating\nfactor receptor, are not depleted by these agents, and continue to secrete\n$A$. Represent that as a floor:\n\n$$\nk_{\\rm syn} g(B_{\\rm tissue}) = k_{\\rm syn}\\left[(1 - \\phi)\\, \\frac{B_{\\rm tissue}}{B_{\\rm tissue,0}} + \\phi \\right]\n$$\n\nwith $\\phi_i$ the fraction of autoantibody production in patient $i$ that\nsurvives complete B-cell depletion. $\\phi_i$ is what separates a responder\nfrom a non-responder, it is a between-patient random effect, and it is not\nidentified from an eight-week observation window. Its image in the reduced\nmodel of Section 8.4 is $\\eta_i \\approx 1 - \\phi_i$, and Section 12 makes that\nthe mixture parameter.\n\n### 8.4 The reduced model a small dataset can support\n\nSections 8.2 and 8.3 chained together carry more parameters than fifty\npatients will support. The model that gets fit collapses the tissue and\nautoantibody layers into one delayed signal, defined here in words before the\nequation.\n\n**The depletion signal $u(t)$.** $u(t) = 1 - B(t)/B_0$, where $B$ is the\ncirculating B-cell count and $B_0$ its baseline. It is 0 before dosing, 1\nwhen B cells are fully depleted, and returns toward 0 as they repopulate. It\nis what the B-cell layer hands to the platelet layer, and it is observed.\n\n**The transduced signal $Z(t)$.** $u(t)$ passed through a first-order lag\nwith rate $k_{e0}$:\n\n$$\n\\frac{dZ}{dt} = k_{e0}\\,\\big(u(t) - Z\\big), \\qquad Z(0) = 0\n$$\n\n$Z$ lies between 0 and 1 and follows $u$ with a delay of about $1/k_{e0}$.\nIt stands in for everything between depletion of circulating B cells and a\nchange in platelet destruction that the study does not measure: depletion in\nspleen and marrow, the turnover of plasmablasts, and the decay of the\nautoantibody they made. A $k_{e0}$ half-life of about six weeks reproduces\nrituximab's time to response (Section 3.5). $Z$ is not the drug effect on\nB cells, which Section 8.2 writes as $S \\cdot \\log(1 + C/C_{\\rm ref})$; it\nis one layer further down.\n\n**How $Z$ moves the destruction rate.** $k_{\\rm dest}(t)$ is the loss rate\nof circulating platelets in the last equation of Section 8.3,\n$dP/dt = k_{\\rm tr} P_3 - k_{\\rm dest}(t)\\, P$. The platelet chain is\nunchanged from 8.3; the reduced model changes only what drives\n$k_{\\rm dest}$, replacing the latent autoantibody $A(t)$ with $Z(t)$:\n\n$$\nk_{\\rm dest}(t) = k_{\\rm dest,0}\\left(1 + \\theta_i \\left[1 - \\eta_i Z(t)\\right]\\right)\n$$\n\nBefore dosing, $Z = 0$ and $k_{\\rm dest} = k_{\\rm dest,0}(1 + \\theta_i)$:\nthe patient's untreated excess destruction, with $\\theta_i$ set by the\npre-treatment platelet count. At full transduced depletion, $Z = 1$ and\n$k_{\\rm dest} = k_{\\rm dest,0}(1 + \\theta_i(1 - \\eta_i))$: the drug has\nremoved a fraction $\\eta_i$ of the excess. A good fit has $\\theta_i$ of\nseveral-fold, since untreated ITP platelet counts are a small fraction of\nnormal, and $\\eta_i$ near 1 in a responder and near 0 in a non-responder.\n\nThree parameters remain on the drug side: $k_{e0}$, taking an informative\nprior from published time to platelet response after rituximab in ITP;\n$\\theta_i$, identified from the pre-treatment platelet count; and\n$\\eta_i \\in [0, 1]$, the fraction of that severity the drug can remove in\npatient $i$. $\\eta_i$ is the mixture. Its image in the full model is $1 - \\phi_i$, where\n$\\phi_i$ (Section 8.3) is the fraction of the patient's anti-platelet\nantibody that is made by long-lived plasma cells, which carry neither CD20\nnor BAFF-R and are not depleted; a patient with $\\phi_i$ near 1 keeps making\nthe antibody after every B cell is gone, and is the non-responder.\n\nThis mixture has a published name and a precedent. The eltrombopag ITP model\n(references, entry 26) put a mixture on the drug-effect slope, estimated 81%\nresponders with 19% at slope zero, and then used the fitted model to simulate\nresponse-guided titration. Section 8.4 is that model with the drug effect\nmoved from production to destruction and the lag lengthened from two weeks to\nsix.\n\n**This reduction is the specification's main structural assumption, and\nSection 15 tests it against data generated from the unreduced model.** If\nthe reduced model recovers the right dose from data generated by the full\none, the reduction is safe at this sample size. If it does not, the answer to\nthe project's question is no for the reason given in Section 17.\n\n### 8.5 Which intermediate layers to observe, and whether the chain beats a direct link\n\nSerum IgG is measured in this study, circulating B cells are measured, and an\nanti-platelet antibody assay may be. The question is whether fitting the chain\ndrug → B cells → IgG → platelets does better than fitting drug → platelets\nwith everything between collapsed into the effect compartment of Section 8.4.\n\n**The rule.** An intermediate layer helps when it is measured, sits on the\ncausal path, and is less noisy than the endpoint it feeds. It costs a\nparameter or two and a set of residuals. Each of the three layers scores\ndifferently against that.\n\n**Circulating B cells: include.** Measured at every visit, on the causal\npath, and near-noiseless below the limit of quantification. The time to\nrepopulation $T_{\\rm rep}$ is the cleanest dose-dependent quantity in the\nstudy (Section 7), and a model without the B-cell layer has to recover the\nsame information from platelet counts, which it cannot. This layer is easy to\nfit, and that matches experience with B-cell depleting agents generally.\n\n**Serum total IgG: include as a covariate, not as a link.** It is measured\nand it is cheap, and for a B-cell depleting agent it is the wrong variable. Total\nIgG is maintained by long-lived plasma cells that carry neither CD20 nor the\nB-cell activating factor receptor, so it falls slowly and modestly after\ndepletion, months behind the B cells, and the anti-platelet fraction of it is a\nsmall part of the total. For an FcRn blocker total IgG is the whole mechanism\nand the efgartigimod model stops there for good reason (references, entry 25);\nfor a depleting agent it is a lagging summary of the plasma-cell compartment.\nIts use here is as the observable that identifies the long-lived plasma cell\nfloor $\\phi_i$ in Section 8.3: a patient whose total IgG does not move after\ncomplete depletion has a large $\\phi_i$, and that is information the platelet\ncount alone gives only after months. This is why Ig is harder to model than B\ncells for this class: the drug barely moves it.\n\n**Anti-platelet IgG: include as the observed $A(t)$ where the assay is\npositive, and expect it to be positive in about half the patients.** The\nassays are outside pharmacometrics, so from zero. The platelet-associated IgG\ntest (PAIgG) measures all IgG bound to the patient's platelets and is\nnon-specific, elevated in most thrombocytopenias of any cause, and not useful\nhere. The monoclonal antibody immobilization of platelet antigens assay\n(MAIPA) captures antibody bound to a named platelet glycoprotein, usually\nGPIIb/IIIa or GPIb/IX, and is specific for ITP. Its limitation is\nsensitivity: it is positive in roughly half to 60% of patients with a clinical\ndiagnosis of ITP, it is semi-quantitative, and it is run at baseline rather\nthan serially in most trials. None of those figures has been checked against a\nsource (references, entry 30). Where it is positive and serial, it is $A(t)$\nmeasured, the latent state of Section 8.3 becomes an observed one, and the\nmodel can see a patient's autoantibody fall before the platelet count rises.\nThat is the one measurement in the study that would let the model separate a\nslow responder from a non-responder early, which is the identifiability\nproblem in Section 10.\n\n**Does the chain beat the direct link?** With B cells alone: yes, and by a\nmargin that has nothing to do with platelets, because the B-cell layer is\nwhere the dose enters. With total IgG added: marginally, as a covariate on\n$\\phi_i$. With anti-platelet IgG added, serially, in the patients who have it:\nthis is the case where the chain would clearly win, and it is also the case\nthat has never been run in a trial of a B-cell depleting agent in ITP. The\nsimulation in Section 15 should carry a version of the dataset with $A(t)$\nobserved in half the patients and report how much the sample size in Section\n14 falls, since that number is the argument for putting the assay in the\nprotocol.\n\n## 9. What the dataset has to contain\n\nThe model above is a set of requirements on the study, and a study that does\nnot meet them cannot be rescued by analysis. Stated as requirements so that\nthey can be checked against a real protocol before any fitting.\n\n| # | Requirement | Why the model needs it | If absent |\n|:--|:---|:---|:---|\n| 1 | At least three dose levels with $\\ge 3$ patients each | Any dose-response at all | Fatal |\n| 2 | A top dose at least 4-fold above the bottom dose | $T_{\\rm rep}$ separation between levels | Fatal |\n| 3 | B-cell counts weekly for 8 weeks, then monthly to repopulation | $k_{\\rm out}$, and therefore $T_{\\rm rep}$ | Fatal |\n| 4 | Follow-up past B-cell repopulation in most patients | $T_{\\rm rep}$ is right-censored otherwise | Severe |\n| 5 | Platelet counts at every visit, 6 months minimum | Separating responders from non-responders | Fatal |\n| 6 | Pre-treatment platelet counts, $\\ge 2$ per patient | $\\theta_i$, the baseline severity | Severe |\n| 7 | Rescue therapy dates and doses | Platelet rises not attributable to drug | Severe |\n| 8 | Concomitant TPO-RA and corticosteroid exposure recorded | The largest competing platelet driver | Severe |\n| 9 | Serum total IgG at every visit | Identifies the plasma-cell floor $\\phi_i$ (Section 8.5) | Valuable |\n| 9a | Anti-platelet IgG by MAIPA, serially, where positive at baseline | Makes $A(t)$ observed rather than latent (Section 8.5) | Valuable |\n| 10 | Immature platelet fraction | Separates production from destruction | Valuable |\n\n: Data requirements, in decreasing order of consequence {tbl-colwidths=\"[5,35,38,12]\"}\n\nRequirement 10 deserves the argument it gets in Section 12. Immature platelet\nfraction (IPF) is the proportion of circulating platelets with residual RNA,\nmeasurable on a standard haematology analyser, and it stands to thrombopoiesis\nas the reticulocyte count stands to erythropoiesis. In ITP it is characteristically\nelevated, because destruction is high and the marrow is compensating. A drug\nthat lowers destruction should lower IPF while raising platelet count, and a\ndrug that raised production would raise both. That is a structural\nidentifiability question answered by one extra number on a blood count that\nwas drawn anyway.\n\n## 10. Identifiability\n\nThree parameters in Section 8.4 compete to explain the same feature of the\ndata, which is that some patients' platelet counts rise weeks after dosing and\nothers' do not.\n\n**$k_{e0}$ against $\\eta_i$.** A slow transduction rate and a partial drug\neffect both flatten the platelet trajectory. They separate only if follow-up\nextends past the point where a slow response would have completed, which is\nrequirement 4 in Section 9 restated on the platelet side. Fix $k_{e0}$ from\nthe literature prior and estimate $\\eta_i$; the reverse is not supportable.\n\n**$\\eta_i$ against $\\theta_i$.** Baseline severity and drug effect are\nseparated by the pre-treatment platelet counts and by nothing else, which is\nrequirement 6.\n\n**$EC_{50}$ against $E_{\\max}$ in the B-cell layer.** Not separable at doses\nthat all saturate, for the reason in Section 6.2, and the model is\nparameterized as a slope so that the question does not arise. It arises again\nonly if the lowest escalation cohort has a quantifiable nadir, which is an\nargument for a low starting dose that a pure safety argument would not make.\nThe diagnostic that replaces the $EC_{50}$ profile is a profile likelihood on\nthe slope $S$, and it is expected to be wide.\n\nReport all three as identifiability diagnostics on every simulated fit, not as\nprose: condition number of the Fisher information matrix, the profile\nlikelihood for the slope $S$ and for $k_{\\rm out}$, and the correlation\nbetween the $\\eta_i$ and $\\theta_i$ empirical Bayes estimates.\n\n## 11. Exposure-response confounding\n\nAn exposure-response analysis of an escalation-plus-expansion study is a known\ngenerator of false positives, and the review literature on time-dependent\nclearance in therapeutic antibodies names the two mechanisms that apply here.\n\n**Target burden drives clearance.** B cells are the target sink. A patient with\na high B-cell burden clears the drug faster and therefore has both lower\nexposure and, plausibly, more disease to remove. Exposure and outcome then\ncorrelate for a reason that has nothing to do with dose. The PK model in\nSection 8.1 is linear and does not carry this mechanism; baseline B-cell count\nis tested as a covariate on clearance so that the correlation is named rather\nthan left in the residual, and the selection rule below is written on dose\nrather than exposure so that it cannot act on the decision.\n\n**An expansion with few arms is close to the worst case.** The published\nreview finding is that designs with one tested dose level have a high\nprobability of a false-positive exposure-response result, because all the\nexposure variation is between-patient and between-patient exposure variation\nis confounded with everything else about the patient. Two to four arms are\nbetter than one and still leave most of the exposure spread inside arms.\n\nThe consequence for the analysis plan is a rule, not a caution. **Dose, not\nexposure, is the independent variable in the dose selection rule of Section\n13.** Individual exposure enters the model as the thing dose produces, and the\nselection is made by simulating dose levels forward from the fitted model\nrather than by regressing outcome on observed area under the concentration\ncurve. An exposure-response plot may be produced as a diagnostic; it does not\nselect a dose.\n\n## 12. Choice of endpoint for fitting\n\nThe Phase 2 and Phase 3 endpoints in ITP are dichotomies. Durable response as\nplatelet count $\\ge 50 \\times 10^9$/L over a specified share of weeks is what\ngets reported and what a label carries. Fitting that dichotomy directly at\nPhase 1 sample sizes wastes most of the information in the dataset, and the\nstatistical literature on dichotomizing continuous outcomes quantifies the\nloss.\n\nThe rilzabrutinib FDA review (references, entry 22) shows the two endpoints\ndisagreeing on the same 305 patients: the continuous change in platelet count\nrose with exposure, and the durable-response dichotomy was flat across\nexposure quartiles. The fostamatinib reviews show the same thing at 79\npatients, where a slope at Week 12 had vanished by the Week 14 to 24 window.\n\n**Fit the continuous longitudinal platelet count; derive the dichotomy from\nthe fitted model by simulation.** The mixture in Section 8.4 does the work\nthat a responder analysis does by hand: $\\eta_i$ near 0 is a non-responder,\nand the population distribution of $\\eta$ is what a response rate is a\none-number summary of. Simulating the Phase 2 endpoint from the fitted model\nthen gives a predicted response rate per dose with an interval, which is what\na Phase 2 decision actually needs.\n\nTwo model features this requires and a plain responder analysis does not:\n\n- **A distribution for $\\eta$ with mass near zero.** A normal random effect on\n  a logit scale will not reproduce a bimodal response. Candidates are a\n  two-component mixture and a beta distribution with both shape parameters\n  below one. Fit both; report both.\n- **Rescue therapy as informative censoring.** A patient rescued for a low\n  platelet count is not missing at random. Model the rescue as an event with a\n  hazard driven by the current platelet count, or exclude post-rescue\n  observations and accept the bias, and say which.\n\n## 13. The dose selection rule\n\nStated in advance, so that the simulation in Section 15 scores something\nfixed.\n\n**Select the lowest dose whose posterior predictive Phase 2 response rate is\nwithin 5 percentage points of the maximum over the dose range studied, with at\nleast 80% posterior probability.**\n\nThree properties of that rule, each deliberate.\n\nIt targets the bottom of the plateau rather than the maximum, which is the\nquantity Section 7 argues the data can locate. It uses the predicted clinical\nendpoint rather than $T_{\\rm rep}$, so that the biomarker's role stays limited\nto carrying dose information into the model. And it is asymmetric, because 5\npercentage points below the maximum is a tolerance on the downside only.\n\n**The comparator rules the simulation scores this against:**\n\n| Rule | Basis |\n|:---|:---|\n| A. Highest safe dose | The default when no model is built |\n| B. Lowest dose with $T_{\\rm rep}$ within 10% of maximum | Biomarker-only, no platelet model |\n| C. The rule above | The model this specification proposes |\n| D. Empirical best observed response rate | What the raw data says, no model |\n\n: Dose selection rules compared in Section 15 {tbl-colwidths=\"[45,55]\"}\n\nRule A is the baseline. If C does not beat A by enough to change a decision,\nthe project's answer is that the model should not be built, and that is a\npublishable finding.\n\n## 14. How many patients, with and without the model\n\nThe question in Section 6 has a cost attached. If the model cannot be built,\nthe dose is chosen from response rates per arm, and this section says what\nthat takes. If the model can be built, it earns its place by needing fewer\npatients than that, and this section bounds how many fewer. The numbers are\ncomputed here rather than quoted, and the\n[Sizing Studies](../sizing-studies/sizing-studies.qmd) page carries the\ngeneral method they follow.\n\n### 14.1 Without a model: picking the best arm from response rates\n\nTwo framings, and they give answers an order of magnitude apart.\n\n**Detecting a difference between two arms** is the hypothesis-test framing,\nand it is the wrong question for dose selection, but it is the number people\nreach for first. Two-sided $\\alpha = 0.05$, 80% power:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairs <- data.frame(p_low = c(.30, .40, .50, .50), p_high = c(.50, .60, .60, .55))\npairs$n_per_arm <- sapply(seq_len(nrow(pairs)), function(i)\n  ceiling(power.prop.test(p1 = pairs$p_low[i], p2 = pairs$p_high[i], power = .8)$n))\nknitr::kable(pairs, col.names = c(\"Lower arm\", \"Higher arm\", \"Patients per arm\"),\n             caption = \"Patients per arm to detect a difference in durable response rate\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Patients per arm to detect a difference in durable response rate\n\n| Lower arm| Higher arm| Patients per arm|\n|---------:|----------:|----------------:|\n|       0.3|       0.50|               93|\n|       0.4|       0.60|               97|\n|       0.5|       0.60|              388|\n|       0.5|       0.55|             1565|\n\n\n:::\n:::\n\n\n**Selecting the best of $K$ arms** is the right framing. The design does not\nneed to prove the top arm is better; it needs to pick it with acceptable\nprobability. Probability of correct selection is the chance that the arm with\nthe highest true rate also has the highest observed count, ties split at\nrandom, when it beats every other arm by $\\delta$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(20260909)\npcs <- function(K, n, p_best, delta, nsim = 20000) {\n  p <- c(p_best, rep(p_best - delta, K - 1))\n  x <- matrix(rbinom(K * nsim, n, p), nrow = nsim, byrow = TRUE)\n  mx <- apply(x, 1, max)\n  mean((x[, 1] == mx) / rowSums(x == mx))\n}\ngrid <- expand.grid(K = c(2, 3, 4), delta = c(.10, .15, .20), n = c(10, 20, 30, 40, 60, 80))\ngrid$pcs <- mapply(pcs, grid$K, grid$n, MoreArgs = list(p_best = .55), delta = grid$delta)\nneed <- aggregate(n ~ K + delta, data = grid[grid$pcs >= .80, ], FUN = min)\nwide <- reshape(need, idvar = \"delta\", timevar = \"K\", direction = \"wide\")\nnames(wide) <- c(\"Margin of best arm\", \"2 arms\", \"3 arms\", \"4 arms\")\nwide[[1]] <- sprintf(\"%.0f points\", 100 * wide[[1]])\nknitr::kable(wide, caption = \"Patients per arm for 80% probability of picking the best arm (best arm 55%)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Patients per arm for 80% probability of picking the best arm (best arm 55%)\n\n|   |Margin of best arm | 2 arms| 3 arms| 4 arms|\n|:--|:------------------|------:|------:|------:|\n|1  |10 points          |     40|     80|     NA|\n|3  |15 points          |     20|     40|     60|\n|6  |20 points          |     10|     20|     30|\n\n\n:::\n:::\n\n\nA blank cell means no value up to 80 per arm reached 80%.\n\nRead against the study in Section 1, which has two expansion arms of 20 to\n40. The two-arm column is the one that applies: 15 points apart is picked\ncorrectly four times in five at 20 per arm, and 10 points apart needs 40 per\narm for the same. Ten points is what the ianalumab 3 against 9 mg/kg\ncomparison and the rituximab low against standard dose comparison both look\nlike (Section 7), so the study as designed sits at the edge of what its raw\nresponse rates can decide. The three- and four-arm columns say what adding\narms would cost, and it is a lot.\n\n**Locating a plateau by comparing arms is not possible at any Phase 1/2\nsize.** The plateau's defining property is that adjacent arms differ by\nlittle. Two arms 5 points apart need\n\n\n::: {.cell}\n\n```{.r .cell-code}\nceiling(power.prop.test(p1 = .50, p2 = .55, power = .8)$n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1565\n```\n\n\n:::\n:::\n\n\npatients per arm to separate. The empirical strategy therefore cannot find\nthe bottom of the plateau; it can only pick the highest tolerated dose and\ncall that the answer, which is comparator rule A in Section 13.\n\n### 14.2 With a model: where the patients are saved, and where they are not\n\nA model changes the arithmetic in two places and leaves it alone in a third.\n\n**Pooling the escalation cohorts and both expansion arms through one\ndose-response shape.** Comparing the two expansion arms uses those two arms'\npatients. Fitting a monotone dose-response through the escalation cohorts as\nwell uses every patient in the study to estimate the contrast between the two\nexpansion doses. For five dose levels at two-fold spacing, 4 patients per\nlevel from the escalation, and the expansion sitting on the top two levels,\nthe variance of the estimated difference between the two expansion doses under\na logistic dose-response linear in log dose, by Fisher information and the\ndelta method, compared to the same difference from the two expansion arms\nalone:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrel_eff <- function(p_top, delta, x, n) {\n  K <- length(x); logit <- function(p) log(p / (1 - p))\n  b <- (logit(p_top) - logit(p_top - delta)) / (x[K] - x[K - 1])\n  a <- logit(p_top) - b * x[K]\n  p <- plogis(a + b * x); w <- n * p * (1 - p)\n  info <- rbind(c(sum(w), sum(w * x)), c(sum(w * x), sum(w * x^2)))\n  g <- c(p[K] * (1 - p[K]) - p[K - 1] * (1 - p[K - 1]),\n         x[K] * p[K] * (1 - p[K]) - x[K - 1] * p[K - 1] * (1 - p[K - 1]))\n  v_model <- drop(t(g) %*% solve(info) %*% g)\n  v_pair  <- p[K] * (1 - p[K]) / n[K] + p[K - 1] * (1 - p[K - 1]) / n[K - 1]\n  v_pair / v_model\n}\nx <- 0:4                                    # five levels, two-fold spacing\ngrid <- expand.grid(n_exp = c(20, 30, 40), delta = c(.05, .10, .15, .20))\ngrid$factor <- mapply(function(ne, d) rel_eff(.55, d, x, c(4, 4, 4, 4 + ne, 4 + ne)),\n                      grid$n_exp, grid$delta)\nwide <- reshape(grid, idvar = \"delta\", timevar = \"n_exp\", direction = \"wide\")\nnames(wide) <- c(\"Margin between expansion doses\", \"20 per arm\", \"30 per arm\", \"40 per arm\")\nwide[[1]] <- sprintf(\"%.0f points\", 100 * wide[[1]])\nknitr::kable(wide, digits = 1,\n             caption = \"Information gained on the expansion contrast by fitting all cohorts through one logistic shape, as a factor\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Information gained on the expansion contrast by fitting all cohorts through one logistic shape, as a factor\n\n|   |Margin between expansion doses | 20 per arm| 30 per arm| 40 per arm|\n|:--|:------------------------------|----------:|----------:|----------:|\n|1  |5 points                       |        6.4|        5.0|        4.2|\n|4  |10 points                      |        5.2|        4.1|        3.5|\n|7  |15 points                      |        3.8|        3.1|        2.6|\n|10 |20 points                      |        2.7|        2.3|        2.0|\n\n\n:::\n:::\n\n\nThat factor is the pooling gain, and three things about it. It is large\nbecause a two-parameter shape over a sixteen-fold dose range is a strong\nassumption, and the escalation cohorts pin the shape at the bottom where the\nexpansion has no patients. It falls as the expansion grows, because the\nexpansion arms then carry most of the information anyway. And it holds only\nif the dose-response has the assumed shape: a plateau shape with a third\nparameter pools less, and a model with the wrong shape borrows strength from\ncohorts that are not informative about the contrast and returns a confident\nwrong answer. Section 15's wrong-structure case is the check on that, and it\nis where the factor above gets replaced by a measured one.\n\n**Using every platelet count instead of one responder call.** The responder\ndichotomy discards the trajectory. The rilzabrutinib FDA review shows the\ncontinuous change in platelet count carrying an exposure signal that the\ndichotomy did not (references, entry 22), and the augmented-binary literature\nputs the gain from the continuous component at a third or so of the sample\nsize (entry 20). In this model the gain is bounded, and the bound is the third\nplace.\n\n**The Bernoulli ceiling.** If a patient is a responder or is not, and the\nmodel's $\\eta_i$ is near 0 or near 1, then once the responder status is known\nthe trajectory adds nothing to the dose-response estimate. The information per\npatient is that of one coin flip with probability $P(\\eta_i \\approx 1 \\mid\n\\text{dose})$, and no model changes that. What the continuous data does is\nclassify the coin flip with fewer errors than a threshold on noisy counts\ndoes, and shorten the follow-up needed to classify it. Where the mixture is\nsharp, the model's whole gain is the pooling factor above; where the mixture\nis soft, with graded partial responders, the trajectory carries dose\ninformation of its own and the gain is larger. Which of those describes\nB-cell depletion in ITP is not known, and the rituximab response\ndistributions in entry 9 are where to look.\n\n### 14.3 The scoping table\n\nPutting the pieces together for the study in Section 1, two expansion arms\nwith the better one at 55% and the margin between them at $\\delta$:\n\n| Question | Without the model | With the model, shape correct | With the model, shape wrong |\n|:---|:---|:---|:---|\n| Pick the better arm, $\\delta$ = 20 | 10 per arm | 10 per arm; nothing to gain | Same |\n| Pick the better arm, $\\delta$ = 15 | 20 per arm | Under 20 per arm | Worse than without |\n| Pick the better arm, $\\delta$ = 10 | 40 per arm | About 20 per arm, from pooling with the escalation | Worse than without |\n| Locate the plateau bottom, $\\delta$ = 5 | Not possible | Only as a shape parameter, and Section 15 says whether it is identified | Confidently wrong |\n\n: What the model buys, by question, in patients per arm {tbl-colwidths=\"[30,20,28,22]\"}\n\nThe middle column applies the pooling factor to the selection table with a\ndiscount for the plateau shape pooling less than the logistic, and the\nsimulation in Section 15 replaces it with a measured number. The right-hand\ncolumn is the case Section 17 is written for.\n\n**The scoping verdict.** ⚠️ Two expansion arms of 20 to 40 can pick between\ndoses 15 or more points apart without any model. Between doses 10 points\napart, 40 per arm does it on the raw rates and 20 per arm does it only with a\nmodel whose dose-response shape is right, so the model is what makes the\nsmaller study sufficient. Locating a plateau bottom is beyond both, except as\na parameter of an assumed shape. Build the model when the two candidate\ndoses are expected to be close, and build it only after the simulation in\nSection 15 has shown that its shape assumption survives being wrong.\n\n## 15. The simulation study\n\nThis is the work. Everything above is the structure it needs.\n\n**15.1 Generate.** Simulate escalation-plus-expansion datasets from the full\nmodel of Sections 8.1 to 8.3, not the reduced model of 4.4. Vary, in a\nfactorial:\n\n- number of dose levels (3, 4, 5) and patients per level (3, 6);\n- expansion size (20, 40) and which dose it sits at;\n- true shape of the dose-response on $\\eta$: plateau at the second dose level,\n  plateau at the fourth, monotone with no plateau in range;\n- the long-lived plasma cell floor $\\phi$, which sets the ceiling on response\n  rate;\n- follow-up duration (6, 12 months).\n\n**15.2 Fit.** The reduced model of Section 8.4, with the priors named there,\nto every simulated dataset. Record convergence, the identifiability\ndiagnostics of Section 10, and the posterior predictive response rate per dose.\n\n**15.3 Score.** For each of the four rules in Section 13:\n\n- probability the selected dose equals the true plateau bottom;\n- probability the selected dose is below it, which is the costly error;\n- expected number of dose levels above it, which is the cheap error;\n- the same three under the wrong-structure case, where data came from a model\n  with tissue depletion lagging peripheral depletion and the fitted model\n  assumes they coincide.\n\n**15.4 Report.** The factorial has too many cells for a figure each. The\noutput is a single figure with true plateau position on the horizontal axis and\nprobability of correct selection on the vertical, one line per rule, one panel\nper sample size. The tables are the supporting detail.\n\n## 16. External checks\n\nTwo published results the model should be able to reproduce, and neither is\nused in fitting.\n\n**VAYHIT2, ianalumab at 3 and 9 mg/kg in ITP.** The 12-month\nfreedom-from-treatment-failure probabilities reported for the two doses differ\nby a few percentage points, against a larger gap to placebo. A model fit to\nescalation data covering that range should predict a plateau below 3 mg/kg. If\nthe model instead predicts a meaningful gain from 9 mg/kg over 3 mg/kg, it is\nwrong in the direction that costs patients drug exposure for nothing, and the\nreason it is wrong is diagnostic.\n\n**Low-dose against standard-dose rituximab in ITP.** Pooled response rates for\n100 mg weekly and 375 mg/m² weekly are close, across a roughly four-fold dose\nrange, in a meta-analysis of a few hundred patients. Same test, different\ncompound and a much longer literature.\n\nBoth checks are on the plateau's existence, not its exact position, which is\nthe strongest claim aggregate published data can support.\n\n## 17. What would make the answer no\n\nWritten before the work, so that a negative result is recognizable rather than\nexplained away.\n\n**Tissue depletion does not track peripheral depletion.** If the dose-response\nthe platelet endpoint depends on is in the spleen, and the spleen is\ninvisible, peripheral B-cell kinetics is a biomarker of the wrong compartment, and no amount of platelet\nmodelling recovers the missing dose axis. This is the most likely route to a\nnegative answer and Section 15.3's wrong-structure case is what detects it.\n\n**The response mixture is not identifiable at $n \\approx 40$.** If the\nposterior for the $\\eta$ distribution is dominated by its prior across every\nsimulated dataset, the predicted response rates per dose carry no information\nthat the raw response counts did not, and rule C reduces to rule D.\n\n**The plateau is outside the studied range.** If the true dose-response is\nstill rising at the top escalation dose, every rule selects the top dose and\nthe model adds nothing. The simulation includes this case so that the\nfrequency with which it can be *detected* is reported, which is a different\nand more useful quantity than the frequency with which it is handled.\n\n**Concomitant therapy dominates.** Most ITP patients entering an escalation\nstudy are on a TPO-RA or corticosteroids or both. If the platelet trajectory\nis mostly explained by those, the drug effect is a small perturbation on a\nlarge signal and the sample size required moves out of reach.\n\n## 18. Milestones\n\n1. **Read the platelet-side literature and fix the platelet parameters.**\n   Entries 1 to 3 of the reading queue. Ends with a table of $k_{\\rm tr}$,\n   $k_{\\rm dest,0}$ and platelet lifespan with a source per number.\n2. **Read the B-cell-side literature and fix the depletion parameters.**\n   Entries 4 to 6. Ends with $k_{\\rm out}$, a prior on $EC_{50}$, and a\n   plausible $T_{\\rm rep}$ against dose curve.\n3. **Set the prior on $k_{e0}$.** Entry 7, the rituximab ITP time-to-response\n   literature. One number and an interval.\n4. **Build the full generative model and show it reproduces ITP.** Untreated\n   platelet counts in the observed range, a response in four to eight weeks, a\n   response rate in the published range at a saturating dose.\n5. **Build the reduced model and fit it to one simulated dataset.** The\n   identifiability diagnostics of Section 10 on a single case before any\n   factorial.\n6. **Run the factorial and produce the Section 15.4 figure.**\n7. **Run the external checks of Section 16.**\n\nMilestones 1 to 3 are reading and produce a parameter table. Milestone 4 is\nwhere the specification first meets contact with reality, and Sections 8 and 9\nare expected to change there.\n\n## 19. Why no such model has been published\n\nPlatelet count is the primary endpoint of every ITP trial, so the absence of a\nPK-platelet model for any immunomodulatory agent in ITP needs an explanation\nbefore the project assumes it can build one.\n\n**The published PK-platelet models in ITP are all for drugs that stimulate\nplatelet production, and none is for a drug that blocks platelet\ndestruction.** Seven reasons, ranked by how much each one would still bite\nthis project. The evidence for each is in\n[references.qmd](references.qmd).\n\n**1. The mechanism that got modelled is the one with a graded dose-response.**\nA thrombopoietin receptor agonist raises $k_{\\rm prod}$ in Section 8.3\ndirectly, continuously, and with a lag of days. Every patient's platelet count\nmoves, the size of the move scales with dose, and the loop from dose to\nresponse closes inside two weeks. That is a textbook indirect-response\nproblem, and the eltrombopag, romiplostim, avatrombopag and lusutrombopag\nmodels exist because of it. An immunomodulator acts on $k_{\\rm dest}$ through\nan unmeasured autoantibody with a peak-response lag of 14 to 180 days\n(Section 3.5).\n\n**2. The endpoint is a dichotomy of a dichotomy.** CR and R are thresholds on\nplatelet count, and recent trials add a durability requirement over 8 to 12\nweeks on top. What is reported is a proportion at one dose. A proportion at\none dose is not something a model is needed for.\n\n**3. The response is a mixture, not a graded effect.** Dose moves the\nprobability that a patient responds, not the size of the rise in a patient who\ndoes. Continuous $E_{\\max}$ machinery fits the wrong shape, and the\ninformation per patient in a binary outcome is low enough that Phase 1 sample\nsizes give little to fit.\n\n**4. Doses are titrated to the endpoint.** Thrombopoietin receptor agonists\nand fostamatinib are dose-adjusted to hold platelets in a window. Dose then\ndepends on response, which inverts the direction a standard exposure-response\nanalysis assumes and makes the observed relationship uninterpretable without a\nmodel of the adjustment rule itself.\n\n**5. Dose-ranging designs in ITP destroy the dose contrast.** The rilzabrutinib\nPhase 1/2 dose-finding study used intrapatient escalation across four dose\nlevels, so dose is confounded with time on drug within every patient. The\norelabrutinib Phase 2 randomized two doses and is the exception.\n\n**6. Sponsors tried platelets first, fell back to the clean biomarker, and\nthe regulators accepted the fallback.** The PMDA review of efgartigimod\nrecords that argenx built a model from total IgG to platelet count on the\nPhase 2 data, that \"there was marked variation in the interindividual platelet\ncount\" the model could not explain, and that the Phase 3 dose was therefore\nchosen on IgG reduction (references, entry 25). Ianalumab's Phase 2b doses in\nSjögren's were chosen from B cells and tissue receptor occupancy (entry 2).\nRilzabrutinib's 400 mg BID came from BTK occupancy plateaus in mouse and human\nplus the raw Part A response by dose, and the platelet model was built\nafterwards to confirm it (entry 22). In every case the fast, continuous,\nsaturable biomarker made the decision. This specification proposes going one\nlink further, and Sections 7 and 17 are why that is hard.\n\n**7. Where the continuous model was attempted, the reviews record it\nfailing, except once.** For fostamatinib, \"none of the applicant's attempted\nmodels including semi-mechanistic, direct response, and indirect response\nmodel were successful for the platelet count analysis as a continuous\nvariable\" (FDA, entry 23), and \"it was not possible to fit a continuous PK/PD\nmodel for the platelet count-time profiles\" (EMA, entry 24). What survived was\nlogistic regression at Week 12 on 79 patients, which the FDA read as a\nrelationship and the CHMP read as none. The exception is rilzabrutinib, where\nan indirect exposure-response model on 10,652 platelet counts from 305 patients\nfit adequately (entry 22). It had ten times the patients of a Phase 1 study,\none dose, and a mechanism with a 36-day median time to response instead of\nrituximab's 14 to 180 days to peak.\n\n**The regulatory reviews have now been read, and they close the gap in one\ndirection.** The absence of a published model is not because nobody tried.\nThree sponsors tried, with Phase 2 or Phase 3 data, and the reviews say what\nhappened. What remains open is whether a model built to find a plateau rather\nthan a slope, with the mixture and the fixed platelet layer of Section 8,\ndoes better at the sample size those three had, which is Section 15.\n\n**What this changes in the specification.** Reasons 2, 3 and 5 are design\nproblems this project can specify around, and Sections 12, 13 and 15 do. Reason\n1 is the one that cannot be specified around: it is the same delay-and-latency\nproblem as Section 17's first failure mode, seen from the endpoint's side\nrather than the biomarker's.\n\n## 20. The intended use\n\nA pharmacometrician holding escalation and expansion data on a B-cell\ndepleting agent in ITP, being asked for a Phase 2 dose. This document says\nwhat such a model can and cannot deliver, what the study has to have measured\nfor it to be buildable, and how often it beats picking the highest safe dose.\n\nThe expected finding, which Section 15 tests rather than assumes, is that the\nmodel locates a plateau boundary the raw response counts cannot resolve at\n$n \\approx 40$, and that it does so only where B-cell repopulation has been\nfollowed to completion.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}