{
  "hash": "d7f82ae9336516a8d1ea3226cc15bd6c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"The model against digitized data\"\nsubtitle: \"Odronextamab cycle 1 to 3, fitted, with one subtype reproduced and one falsified\"\ndescription: \"The first time this project's structural model meets an observed concentration. Figure 4A of the odronextamab population PK paper is digitized, the model is fitted to both B-NHL subtypes, and the result is a good fit for DLBCL that does not identify the target pool and an outright failure for follicular lymphoma.\"\ncategories: [pharmacometrics, pharmacokinetics, simulation, working document]\ndate: last-modified\nexecute:\n  freeze: auto\n  warning: false\n  message: false\ntoc: true\ntoc-depth: 3\ntoc-location: left\nhtml-math-method: mathjax\n---\n\n::: {.callout-important appearance=\"simple\"}\n**The concentrations here are read off a published figure, not measured.**\nThey are medians of observed individual concentrations digitized from Figure\n4A of Kovalenko et al. 2026, which is open access. The axis calibration is\nchecked against the assay limit the figure draws and is good to about one\npixel, or 5% in concentration; the medians themselves carry whatever error\nthe original plotting and the marker centroid introduce. Individual data is\nnot available, so nothing here is a population fit. Sources and their status\nare in [References](references.qmd); the model is specified in\n[One structural model for the class](unified-model.qmd).\n:::\n\n## In brief\n\n**What this is.** The first point in the project where the model meets an\nobservation. Everything before it was a forward simulation.\n\n**The result for DLBCL: the structure fits.** Two estimated parameters\nagainst 18 digitized medians spanning a 250-fold concentration range give a\nresidual standard deviation of 0.22 on the log scale, about a 25%\ncoefficient of variation. The cycle 1 step-up profile, the accumulation\nthrough cycle 3, and the trough depths all come out.\n\n**The result for follicular lymphoma: the structure fails.** Residual\nstandard deviation 0.83, and the fit is driven to a target pool of\n1.6 × 10¹² to 1.7 × 10¹³ cells and a killing rate of 47 to 59 per day.\nThat is more B cells than a person has and a kill rate with no physical\nreading. This is falsifier 2 of the four written down in advance.\n\n**The result with the widest consequences: the target pool is not\nidentifiable.** For DLBCL, placing the target entirely in plasma gives 3.0 mg\nof binding sites and placing 90% of it in tissue gives 27.8 mg, a\nnine-fold range, with residual standard deviations of 0.230 and 0.222. The\ndata cannot tell them apart. Section 4 of\n[the model document](unified-model.qmd) predicted this from the structure;\nhere it is on real observations.\n\n**Out of scope.** No population fit, no between-subject variability, no\ncovariates, no second drug yet.\n\n## 1. The Digitization\n\nFigure 4A of Kovalenko et al. plots observed individual concentrations,\ntheir medians at each nominal time, and the model's median with a 90%\nprediction interval, for the first three weeks, separately for DLBCL and\nfollicular lymphoma. The pink median markers are what is extracted.\n\nThe axis calibration is measured from the image rather than assumed. Tick\nrows come out at 24.0, 68.5, 113.0, 157.5 and 202.4 pixels for 10¹ down to\n10⁻³ mg/L, which is uniform to a fifth of a pixel across four decades. The\nfigure also draws the assay lower limit of quantification, 0.00313 mg/L, as\na dashed line: it is found at row 179.5 and the calibration predicts 180.3.\n**A one-pixel agreement on a quantity the calibration was not fitted to is\nthe check that the mapping is right.**\n\n`digitize_odronextamab.py` in this folder does the extraction and writes\n`data/odronextamab_fig4A_medians.csv`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsuppressMessages({library(rxode2); library(dplyr); library(tidyr)\n                  library(ggplot2); library(xgxr)})\nxgx_theme_set()\nknitr::opts_chunk$set(fig.width = 8, fig.height = 3.8)\nLLOQ <- 0.00313\n\nobs <- read.csv(\"data/odronextamab_fig4A_medians.csv\")\nobs |> count(subtype, name = \"medians\") |>\n  mutate(`at the assay limit` = c(\n    sum(obs$conc_mg_L[obs$subtype == \"DLBCL\"] <= LLOQ*1.12),\n    sum(obs$conc_mg_L[obs$subtype == \"FL\"]    <= LLOQ*1.12)),\n    `concentration range` = c(\n    sprintf(\"%.4g to %.3g mg/L\", min(obs$conc_mg_L[obs$subtype==\"DLBCL\"]),\n            max(obs$conc_mg_L[obs$subtype==\"DLBCL\"])),\n    sprintf(\"%.4g to %.3g mg/L\", min(obs$conc_mg_L[obs$subtype==\"FL\"]),\n            max(obs$conc_mg_L[obs$subtype==\"FL\"])))) |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|subtype | medians| at the assay limit|concentration range   |\n|:-------|-------:|------------------:|:---------------------|\n|DLBCL   |      18|                  0|0.01398 to 3.48 mg/L  |\n|FL      |      14|                  1|0.003262 to 3.75 mg/L |\n\n\n:::\n:::\n\n\n### 1.1 The Regimen, Read Out of the Data\n\nThe paper describes the regimen as 0.7/4/20/160 mg weekly. The digitized\npoints show **two** peaks in each of the first three weeks, the second\nhigher than the first, which a single weekly dose cannot produce. The\nstep-up doses are split across consecutive days, and the split is visible in\nthe medians before it is stated anywhere in the text.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndose <- tibble(day = c(0, 1, 7, 8, 14, 15, 21),\n               amt = c(0.2, 0.5, 2, 2, 10, 10, 160))\ndose |> mutate(week = c(1,1,2,2,3,3,4), .before = day) |> knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n| week| day|   amt|\n|----:|---:|-----:|\n|    1|   0|   0.2|\n|    1|   1|   0.5|\n|    2|   7|   2.0|\n|    2|   8|   2.0|\n|    3|  14|  10.0|\n|    3|  15|  10.0|\n|    4|  21| 160.0|\n\n\n:::\n:::\n\n\nInfusions run one to four hours and the nominal-day sample is predose, so\neach dose starts 0.1 day after its nominal day and runs over two hours.\nGetting this wrong is not cosmetic: comparing a predose trough against a\npost-dose simulated concentration inflated the residual standard deviation\nfrom 0.22 to 1.39 before it was fixed.\n\n## 2. Fitting\n\nThe structure is the one in [the model document](unified-model.qmd).\nDisposition is fixed to the published estimates and $K_{ss}$ is fixed to the\npublished Michaelis constant of 1.95 mg/L. Two parameters are estimated: the\naccessible target pool and the killing rate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nuni <- rxode2({\n  cc <- central/vc\n  ct <- tissue/vt\n  oc <- cc/(kss + cc)\n  ot <- ct/(kss + ct)\n  cltot <- cl + kint*rc*vc/(kss + cc) + kint*rt*vt/(kss + ct)\n  d/dt(depot)   <- -ka*depot\n  d/dt(central) <-  ka*depot - cl/vc*central - qt/vc*central + qt/vt*tissue -\n                    qp/vc*central + qp/vp*periph - kint*rc*vc*oc\n  d/dt(tissue)  <-  qt/vc*central - qt/vt*tissue - kint*rt*vt*ot\n  d/dt(periph)  <-  qp/vc*central - qp/vp*periph\n  d/dt(rc)      <-  kdeg*(rc0 - rc) - (kint + kkill)*rc*oc\n  d/dt(rt)      <-  kdeg*(rt0 - rt) - (kint + kkill)*rt*ot\n  rc(0) <- rc0\n  rt(0) <- rt0\n  f(depot) <- fbio\n})\n\np0 <- c(cl = 0.189, vc = 4.99, vp = 4.42, qp = 1.21,   # published disposition\n        vt = 2.0, qt = 0.3,                            # tissue, assumed\n        kss = 1.95, kint = 1.0, kkill = 1.0, kdeg = log(2)/3,\n        rc0 = 0, rt0 = 0, ka = 100, fbio = 1)\n\nev <- Reduce(function(e, i) e |> et(amt = dose$amt[i], cmt = \"central\",\n                                    time = dose$day[i] + 0.10, dur = 2/24),\n             seq_len(nrow(dose)), et()) |> et(seq(0, 22, by = 0.005))\n\nset_target <- function(p, total_mg, frac_tissue) {\n  p[\"rc0\"] <- total_mg*(1 - frac_tissue)/p[[\"vc\"]]\n  p[\"rt0\"] <- total_mg*frac_tissue/p[[\"vt\"]]\n  p\n}\nfit_one <- function(subtype, frac_tissue) {\n  o <- obs[obs$subtype == subtype & obs$conc_mg_L > LLOQ*1.12, ]  # censored medians dropped\n  f <- function(lp) {\n    q <- set_target(p0, exp(lp[1]), frac_tissue); q[\"kkill\"] <- exp(lp[2])\n    s <- try(as_tibble(rxSolve(uni, q, ev)), silent = TRUE)\n    if (inherits(s, \"try-error\")) return(1e9)\n    pr <- approx(s$time, s$cc, xout = o$day)$y\n    if (any(!is.finite(pr)) || any(pr <= 0)) return(1e9)\n    sum((log(pr) - log(o$conc_mg_L))^2)\n  }\n  best <- NULL\n  for (s0 in list(c(10,1), c(3,.5), c(30,2), c(1,.2), c(100,5))) {\n    r <- optim(log(s0), f, control = list(maxit = 8000, reltol = 1e-12))\n    r <- optim(r$par, f, control = list(maxit = 8000, reltol = 1e-13))\n    if (is.null(best) || r$value < best$value) best <- r\n  }\n  e <- exp(best$par)\n  q <- set_target(p0, e[1], frac_tissue); q[\"kkill\"] <- e[2]\n  list(target_mg = unname(e[1]), kkill = unname(e[2]),\n       sd_log = sqrt(best$value/nrow(o)), n = nrow(o), par = q)\n}\n```\n:::\n\n\nMedians reported at the assay limit are dropped rather than fitted. A median\nplotted on the limit line is censored, and treating it as an equality pulls\nthe fit toward an impossible clearance.\n\n### 2.1 The Overlay\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfits <- lapply(c(DLBCL = \"DLBCL\", FL = \"FL\"), fit_one, frac_tissue = 0.9)\nsim <- bind_rows(lapply(names(fits), function(s)\n  as_tibble(rxSolve(uni, fits[[s]]$par, ev)) |> mutate(subtype = s)))\n\nggplot(sim, aes(time, cc)) +\n  geom_hline(yintercept = LLOQ, linetype = 2, colour = \"grey50\") +\n  geom_line(linewidth = 0.55, colour = \"#2C6FB5\") +\n  geom_point(data = obs, aes(day, conc_mg_L), colour = \"#C0392B\", size = 1.9) +\n  facet_wrap(~subtype) + scale_y_log10() + annotation_logticks(sides = \"l\") +\n  labs(x = \"Days after first dose\", y = \"Odronextamab (mg/L)\")\n```\n\n::: {.cell-output-display}\n![The structural model fitted to digitized observed medians for the first three weeks of odronextamab. Points are digitized medians, the line is the model, the dashed line is the assay limit of quantification. Target 90% in tissue.](digitized-fits_files/figure-html/overlay-1.png){width=768}\n:::\n:::\n\n\nDLBCL is reproduced across the whole cycle 1 step-up, including the\nwithin-week split doses and the depth of each trough. Follicular lymphoma is\nnot: the model cannot fall as fast as the observed week-1 medians and hold\nthe week-2 and week-3 concentrations at the same time.\n\n## 3. Where the Target Sits, Against Real Data\n\nSection 4 of the model document argued that a summary statistic cannot\nidentify the target pool. Here the same question is asked of the profile.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrid <- expand_grid(subtype = c(\"DLBCL\", \"FL\"), frac_tissue = c(0, 0.5, 0.9))\ngrid |>\n  rowwise() |>\n  mutate(f = list(fit_one(subtype, frac_tissue))) |>\n  mutate(`Target pool (mg)` = round(f$target_mg, 2),\n         `Implied cells`    = sprintf(\"%.1e\", f$target_mg/1e3/1.5e5*6.022e23/5e4),\n         `kkill (/day)`     = round(f$kkill, 2),\n         `Residual SD (log)`= round(f$sd_log, 3),\n         n = f$n) |>\n  select(Subtype = subtype, `Fraction in tissue` = frac_tissue,\n         `Target pool (mg)`, `Implied cells`, `kkill (/day)`,\n         `Residual SD (log)`, n) |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|Subtype | Fraction in tissue| Target pool (mg)|Implied cells | kkill (/day)| Residual SD (log)|  n|\n|:-------|------------------:|----------------:|:-------------|------------:|-----------------:|--:|\n|DLBCL   |                0.0|             3.00|2.4e+11       |         0.11|             0.230| 18|\n|DLBCL   |                0.5|             5.68|4.6e+11       |         0.40|             0.222| 18|\n|DLBCL   |                0.9|            27.81|2.2e+12       |         0.61|             0.222| 18|\n|FL      |                0.0|            20.52|1.6e+12       |        46.93|             0.830| 13|\n|FL      |                0.5|            42.59|3.4e+12       |        56.74|             0.837| 13|\n|FL      |                0.9|           216.12|1.7e+13       |        58.89|             0.828| 13|\n\n\n:::\n:::\n\n\n**The placement is unidentifiable and the pool rides on it.** For DLBCL the\nthree placements fit equally well, 0.230 against 0.222 against 0.222, and\nthe target pool they imply runs from 3.0 to 27.8 mg, a factor of nine, or\n2.4 × 10¹¹ to 2.2 × 10¹² cells. Nothing in a concentration-time profile\ndistinguishes a small pool the drug reaches immediately from a large pool it\nreaches slowly, because the product of the two is what the drug sees.\n\nThis is the identifiability result from the model document, confirmed on\nobservations rather than on a simulated summary. It also says what the next\nmeasurement has to be: **a B-cell or tumor-burden time course, not more\nconcentrations.** The target pool is identified by watching the target, and\nthis project has been trying to infer it from the drug.\n\n## 4. The Follicular Lymphoma Failure\n\nWritten against falsifier 2 from Section 6.3 of the model document: *a drug\nneeding a target pool outside the range its receptor density and disease\nburden allow.*\n\nThe follicular lymphoma medians fall from 0.028 mg/L at day 0.21 to 0.0084\nat day 0.98, a factor of 3.3 in 0.77 days, an apparent half-life of 0.45\ndays after a 0.2 mg dose. The structure reaches that only by pushing the\ntarget pool to 1.6 × 10¹² cells and the killing rate to 47 per day, and even\nthen the residual standard deviation is 0.83 and the later concentrations\nare wrong.\n\n| Check | Fitted value | Plausible range | Verdict |\n|:---|:---|:---|:---|\n| Target pool, cells | 1.6 × 10¹² to 1.7 × 10¹³ | ~2 × 10¹¹ total body B cells, plus tumor | ❌ Exceeds by 1 to 2 orders of magnitude |\n| $k_{\\rm kill}$ | 47 to 59 /day | Target-cell killing over hours to days, so order 1 /day | ❌ No physical reading |\n| Residual SD, log scale | 0.83 | 0.22 for DLBCL on the same structure | ❌ Fails on its own terms |\n\n: Falsifier 2 applied to the follicular lymphoma fit {tbl-colwidths=\"[26,26,30,18]\"}\n\nThree readings, and the data here does not separate them.\n\n1. **The digitization is wrong for FL.** Two of the early FL markers are\n   small blobs near the assay limit where the plotted median is least\n   reliable. Checking them against Figure 2's visual predictive check for the\n   FL subpopulation is cheap and comes first.\n2. **The structure is wrong.** Something removes drug fast at very low\n   concentration and has no effect by week 2. A second, higher-affinity and\n   lower-capacity binding site would do it, which is the CD3 arm that Section\n   9.1 of the specification dropped on the evidence of a simulation that had\n   no data in it.\n3. **The published model has the same problem.** Kovalenko et al. fit FL with\n   a $K_v$ covariate of −0.891, making the target decay nearly ten times\n   slower than DLBCL, which is the opposite of what these early medians\n   suggest. Whether their own fit reproduces the FL week-1 medians is\n   answerable from Figure 4A itself and has not been checked.\n\n**Reading 2 is the one that would reopen CD3.** Dropping it was justified by\na simulation, and this is the first observation that argues against the\nsimulation.\n\n## 5. What Changes in the Project\n\n- The **confidence table** in Section 5 of the model document gains a row.\n  The structure now has one subtype it reproduces and one it fails, which is\n  more than it had and less than it needs.\n- The claim that **target burden is the lever** survives for DLBCL and is\n  untested elsewhere, because the pool it implies is unidentifiable within a\n  factor of nine.\n- **CD3 is no longer settled.** It was dropped on simulation evidence, and\n  reading 2 above is the first data-driven argument for putting it back.\n- The **next measurement is not a concentration.** A B-cell or tumor-burden\n  time course identifies the target pool; more concentration-time data does\n  not.\n\n## 6. Next\n\n1. Check the FL early medians against Figure 2's visual predictive check for\n   that subpopulation, which is reading 1 above and the cheapest.\n2. Digitize Figure 4C, the long-term profiles, and refit. Cycle 1 alone\n   cannot see the target destruction that the published $K_v$ describes.\n3. Refit FL with a second binding site restored, and compare on residual\n   standard deviation against the one-site fit.\n4. Then mosunetuzumab, which is where the two-branch ambiguity of Section 4\n   of the model document closes or does not.\n",
    "supporting": [
      "digitized-fits_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}