{
  "hash": "656666d2cb5f71ff33334c72411e344c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"One model across the class\"\nsubtitle: \"A simple target-binding, target-killing model fitted to three T-cell engager settings with one free parameter each\"\ndescription: \"A PK-only model with no CD3 arm: drug distributes into a tissue compartment, binds a target pool present in both compartments, and kills the cells carrying it. Shared parameters are fixed at biologically argued values and only the accessible target burden varies by drug and disease.\"\ncategories: [pharmacometrics, pharmacokinetics, simulation, working document]\ndate: last-modified\nexecute:\n  freeze: auto\n  warning: false\n  message: false\ntoc: true\ntoc-depth: 3\ntoc-location: left\nhtml-math-method: mathjax\n---\n\n::: {.callout-note appearance=\"simple\"}\n**What this is.** One structure, fitted to digitized concentrations from two\npublished figures covering three drug-and-disease settings. Shared parameters\nare fixed at values argued from biology rather than estimated. The accessible\ntarget burden is the only free parameter, except for the mosunetuzumab panel,\nwhich is a single patient and so carries its own clearance and central volume.\nSources and their status are in [References](references.qmd).\n:::\n\n**Scope.** Antibody-like T-cell engagers: intact Fc, neonatal Fc receptor\nrecycling, IgG-scale disposition. Blinatumomab and the albumin-binding and\nImmTAC formats clear on molecular size and are out.\n\n## 1. In Brief\n\n**One structure fits all three settings.** Residual standard deviations on\nthe log scale are 0.26, 0.45 and 0.32, against data spanning 250-fold, 1100-fold\nand 700-fold in concentration.\n\n**The only thing that changes between them is how much target there is.**\n\n| Setting | Accessible target | Implied cells | Residual SD (log) |\n|:---|---:|---:|---:|\n| Odronextamab, follicular lymphoma | 41.2 mg | 3.3 × 10¹² | 0.45 |\n| Odronextamab, DLBCL | 15.1 mg | 1.2 × 10¹² | 0.26 |\n| Mosunetuzumab, one B-NHL patient | 1.4 mg | 1.2 × 10¹¹ | 0.32 |\n\n: One structure, one free parameter per setting {tbl-colwidths=\"[42,16,20,22]\"}\n\nThe ordering is the biologically expected one. Follicular lymphoma is\nindolent and carries the largest CD20-positive burden; DLBCL is aggressive\nwith a smaller one; the mosunetuzumab patient is a single individual\npartway through the range. The spread is about 30-fold across a class where\nthe drugs themselves differ 30-fold in dose.\n\n**No CD3 arm is needed.** The engager and a plain B-cell depleting antibody\nwere indistinguishable in simulation, and nothing in these three fits asks\nfor a second binding site.\n\n**What is not claimed.** The target burden is not identifiable to better\nthan about a factor of ten, because it trades against where the target sits.\nThat is expected rather than a defect: the drug sees the product of pool\nsize and accessibility, not either alone.\n\n## 2. The Model\n\n$$\n\\begin{aligned}\n\\frac{dA_c}{dt} &= -\\frac{CL}{V_c}A_c-\\frac{Q_t}{V_c}A_c+\\frac{Q_t}{V_t}A_t\n- k_{int}R_cV_c\\frac{C_c}{K_{ss}+C_c}\\\\\n\\frac{dA_t}{dt} &= \\frac{Q_t}{V_c}A_c-\\frac{Q_t}{V_t}A_t\n- k_{int}R_tV_t\\frac{C_t}{K_{ss}+C_t}\\\\\n\\frac{dR_j}{dt} &= k_{deg}\\!\\left(R_j^0-R_j\\right)\n-\\left(k_{int}+k_{\\rm kill}\\right)R_j\\frac{C_j}{K_{ss}+C_j},\\quad j\\in\\{c,t\\}\n\\end{aligned}\n$$\n\nTwo drug compartments, a target pool in each, quasi-steady-state binding, and\ntwo ways for a bound receptor to disappear: internalization with the drug on\nit, and killing of the cell carrying it. Five states.\n\n**Why each shared parameter has the value it has.**\n\n| Parameter | Value | Reason |\n|:---|---:|:---|\n| $K_{ss}$ | 1.95 mg/L | The fitted Michaelis constant from the odronextamab population model, about 13 nM for a 150 kDa antibody, mid-range for a T-cell engager tumor-antigen arm |\n| $k_{int}$ | 1 /day | Bound receptor internalized with a half-life near 17 h |\n| $k_{\\rm kill}$ | 1 /day | Target cell killed at saturating occupancy on the same timescale, which is what these drugs do |\n| $k_{deg}$ | 0.23 /day | Target pool turns over with a 3-day half-life |\n| Fraction outside plasma | 0.9 | B cells and plasma cells are overwhelmingly nodal and marrow, not circulating |\n\n: The shared parameter set, fixed and not estimated {tbl-colwidths=\"[16,12,72]\"}\n\nNone of these was tuned to improve a fit. Section 5 shows what happens when\nthey are moved.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsuppressMessages({library(rxode2); library(dplyr); library(tidyr)\n                  library(ggplot2); library(patchwork); library(xgxr)})\nxgx_theme_set()\nknitr::opts_chunk$set(fig.width = 9, fig.height = 6)\n\nm <- rxode2({\n  cc <- central/vc; ct <- tissue/vt\n  oc <- cc/(kss + cc); ot <- ct/(kss + ct)\n  cltot <- cl + kint*rc*vc/(kss + cc) + kint*rt*vt/(kss + ct)\n  d/dt(central) <- -cl/vc*central - qt/vc*central + qt/vt*tissue - kint*rc*vc*oc\n  d/dt(tissue)  <-  qt/vc*central - qt/vt*tissue - kint*rt*vt*ot\n  d/dt(rc) <- kdeg*(rc0 - rc) - (kint + kkill)*rc*oc\n  d/dt(rt) <- kdeg*(rt0 - rt) - (kint + kkill)*rt*ot\n  rc(0) <- rc0; rt(0) <- rt0\n})\nSH <- c(kss = 1.95, kint = 1.0, kkill = 1.0, kdeg = log(2)/3, ftis = 0.9)\n```\n:::\n\n\n## 3. The Data\n\nDigitized from two open-access figures by the scripts in this folder.\nOdronextamab gives observed medians for the first three weeks in two\nsubtypes; mosunetuzumab gives one patient followed for 15 weeks, chosen as\nthe panel with the least residual rituximab competing for CD20.\n\n\n::: {.cell}\n\n```{.r .cell-code}\no1 <- read.csv(\"data/odronextamab_fig4A_medians.csv\")\nsetup <- list(\n  odro_DLBCL = list(cl = .189, vc = 4.99, vt = 4.42, qt = 1.21, tmax = 22,\n    dt = c(0,1,7,8,14,15,21), amt = c(.2,.5,2,2,10,10,160)),\n  odro_FL = list(cl = .189, vc = 4.99, vt = 4.42, qt = 1.21, tmax = 22,\n    dt = c(0,1,7,8,14,15,21), amt = c(.2,.5,2,2,10,10,160)),\n  mosun = list(cl = .584, vc = 5.49, vt = 6.17, qt = 1.46, tmax = 110,\n    dt = c(0,7.12,13.12,21.0,42.4,63.4,84.2,105.2), amt = c(1,2,60,60,30,30,30,30)))\nobs <- list(\n  odro_DLBCL = o1 |> filter(subtype == \"DLBCL\", conc_mg_L > 0.0035) |> transmute(day, conc = conc_mg_L),\n  odro_FL    = o1 |> filter(subtype == \"FL\",    conc_mg_L > 0.0035) |> transmute(day, conc = conc_mg_L),\n  mosun      = read.csv(\"data/mosunetuzumab_fig4a_obs.csv\") |> transmute(day, conc = conc_ug_mL))\ntibble(Setting = names(obs),\n       n = sapply(obs, nrow),\n       `Range (mg/L)` = sapply(obs, function(o) sprintf(\"%.4g to %.3g\", min(o$conc), max(o$conc))),\n       `Fold` = round(sapply(obs, function(o) max(o$conc)/min(o$conc)))) |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|Setting    |  n|Range (mg/L)     | Fold|\n|:----------|--:|:----------------|----:|\n|odro_DLBCL | 18|0.01398 to 3.48  |  249|\n|odro_FL    | 13|0.008437 to 3.75 |  444|\n|mosun      | 19|0.0416 to 29.4   |  708|\n\n\n:::\n:::\n\n\nReading a peak off a log-scale figure carries about a tenth of a day of\nerror, which is enough to put a sample on the wrong side of a dose. Rather than\nmove any data point, each dose is placed just before the first sample that\njumps more than threefold above the one before it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalign <- function(o, dtimes) {\n  o <- o[order(o$day), ]\n  for (k in seq_along(dtimes)) {\n    w <- which(abs(o$day - dtimes[k]) < 0.35); w <- w[w > 1]\n    w <- w[o$conc[w] > 3*o$conc[w-1]]\n    if (length(w)) dtimes[k] <- o$day[w[1]] - 0.06\n  }\n  list(obs = o, dt = dtimes)\n}\n```\n:::\n\n\n## 4. The Fits\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- function(nm, free_disp = FALSE) {\n  d <- setup[[nm]]; al <- align(obs[[nm]], d$dt); o <- al$obs; d$dt <- al$dt\n  ev <- Reduce(function(e, i) e |> et(amt = d$amt[i], cmt = \"central\",\n                                      time = d$dt[i], dur = 2/24),\n               seq_along(d$dt), et()) |> et(seq(0, d$tmax, by = 0.005))\n  f <- function(lp) {\n    cl <- if (free_disp) exp(lp[2]) else d$cl\n    vc <- if (free_disp) exp(lp[3]) else d$vc\n    tot <- exp(lp[1])\n    p <- c(cl = cl, vc = vc, vt = d$vt, qt = d$qt, kss = SH[[\"kss\"]],\n           kint = SH[[\"kint\"]], kkill = SH[[\"kkill\"]], kdeg = SH[[\"kdeg\"]],\n           rc0 = tot*(1 - SH[[\"ftis\"]])/vc, rt0 = tot*SH[[\"ftis\"]]/d$vt)\n    s <- try(as_tibble(rxSolve(m, p, ev)), silent = TRUE)\n    if (inherits(s, \"try-error\")) return(1e9)\n    pr <- approx(s$time, s$cc, xout = o$day)$y\n    if (any(!is.finite(pr)) || any(pr <= 0)) return(1e9)\n    sum((log(pr) - log(o$conc))^2)\n  }\n  starts <- if (free_disp) list(c(5, d$cl, d$vc), c(20, d$cl*2, d$vc*.6), c(1, d$cl*.5, d$vc))\n            else list(1, 5, 15, 40, 100)\n  best <- NULL\n  for (s0 in starts) {\n    lp0 <- log(s0)\n    r <- optim(lp0, f, method = if (length(lp0) == 1) \"Brent\" else \"Nelder-Mead\",\n               lower = if (length(lp0) == 1) log(.01) else -Inf,\n               upper = if (length(lp0) == 1) log(800) else Inf,\n               control = list(maxit = 9000, reltol = 1e-12))\n    if (is.null(best) || r$value < best$value) best <- r\n  }\n  e <- exp(best$par)\n  list(target = unname(e[1]), cl = if (free_disp) unname(e[2]) else d$cl,\n       vc = if (free_disp) unname(e[3]) else d$vc,\n       sd = sqrt(best$value/nrow(o)), n = nrow(o), obs = o, dt = d$dt)\n}\nfits <- lapply(setNames(names(setup), names(setup)), function(n)\n  fit(n, free_disp = (n == \"mosun\")))\n\ntibble(Setting = c(\"Odronextamab, DLBCL\", \"Odronextamab, follicular\",\n                   \"Mosunetuzumab, one patient\"),\n       `Target (mg)` = round(sapply(fits, `[[`, \"target\"), 2),\n       `Implied cells` = sprintf(\"%.1e\", sapply(fits, `[[`, \"target\")/1e3/1.5e5*6.022e23/5e4),\n       `Residual SD (log)` = round(sapply(fits, `[[`, \"sd\"), 3),\n       n = sapply(fits, `[[`, \"n\")) |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|Setting                    | Target (mg)|Implied cells | Residual SD (log)|  n|\n|:--------------------------|-----------:|:-------------|-----------------:|--:|\n|Odronextamab, DLBCL        |       15.05|1.2e+12       |             0.258| 18|\n|Odronextamab, follicular   |       41.18|3.3e+12       |             0.454| 13|\n|Mosunetuzumab, one patient |        1.44|1.2e+11       |             0.321| 19|\n\n\n:::\n:::\n\n\nImplied cells assume 5 × 10⁴ binding sites per cell and a 150 kDa antibody.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlab <- c(odro_DLBCL = \"Odronextamab, DLBCL\", odro_FL = \"Odronextamab, follicular\",\n         mosun = \"Mosunetuzumab, one patient\")\nS <- list(); O <- list()\nfor (nm in names(setup)) {\n  d <- setup[[nm]]; r <- fits[[nm]]\n  ev <- Reduce(function(e, i) e |> et(amt = d$amt[i], cmt = \"central\",\n                                      time = r$dt[i], dur = 2/24),\n               seq_along(r$dt), et()) |> et(seq(0, d$tmax, by = 0.005))\n  p <- c(cl = r$cl, vc = r$vc, vt = d$vt, qt = d$qt, kss = SH[[\"kss\"]],\n         kint = SH[[\"kint\"]], kkill = SH[[\"kkill\"]], kdeg = SH[[\"kdeg\"]],\n         rc0 = r$target*(1 - SH[[\"ftis\"]])/r$vc, rt0 = r$target*SH[[\"ftis\"]]/d$vt)\n  S[[nm]] <- as_tibble(rxSolve(m, p, ev)) |>\n    transmute(day = time, conc = cc,\n              frac = (rc*r$vc + rt*d$vt)/(p[[\"rc0\"]]*r$vc + p[[\"rt0\"]]*d$vt),\n              who = lab[[nm]])\n  O[[nm]] <- r$obs |> mutate(who = lab[[nm]])\n}\nsim <- bind_rows(S) |> mutate(who = factor(who, levels = lab))\nob  <- bind_rows(O)  |> mutate(who = factor(who, levels = lab))\n\ng1 <- ggplot(sim, aes(day, conc)) + geom_line(linewidth = .5, colour = \"#2C6FB5\") +\n  geom_point(data = ob, aes(day, conc), colour = \"#C0392B\", size = 1.7) +\n  facet_wrap(~who, scales = \"free_x\") + scale_y_log10() +\n  annotation_logticks(sides = \"l\") +\n  labs(x = NULL, y = \"Concentration (mg/L)\")\ng2 <- ggplot(sim, aes(day, 100*frac)) + geom_line(linewidth = .5, colour = \"#2E7D5B\") +\n  facet_wrap(~who, scales = \"free_x\") +\n  labs(x = \"Days after first dose\", y = \"Target pool remaining (%)\")\ng1 / g2\n```\n\n::: {.cell-output-display}\n![One structure with one shared parameter set, fitted to three settings by the accessible target burden alone. Upper row, concentration: points are digitized observations, lines are the model. Lower row, the target pool the same fit implies, as a percentage of its starting value.](class-model_files/figure-html/overlay-1.png){width=864}\n:::\n:::\n\n\nThe lower row is the mechanism the upper row is evidence for. The target pool\nsurvives the step-up doses almost intact and then collapses when the first\nfull dose lands: for the mosunetuzumab patient, 60 mg on day 13 takes the pool\nfrom 80% to 12% within a day, and it never recovers.\n\n## 5. How Much the Shared Parameters Matter\n\nThe shared values were argued, not fitted. Moving them one at a time changes\nthe target burden the fit wants and leaves the fit quality alone, which is\nthe expected behaviour of a model whose free parameter absorbs them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsens <- function(par, mult) {\n  keep <- SH; SH[[par]] <<- SH[[par]]*mult\n  r <- fit(\"odro_DLBCL\"); SH <<- keep\n  tibble(Parameter = par, `x` = mult, `Target (mg)` = round(r$target, 2),\n         `Residual SD (log)` = round(r$sd, 3))\n}\nbind_rows(lapply(c(0.3, 1, 3), function(k) sens(\"kkill\", k)),\n          lapply(c(0.3, 1, 3), function(k) sens(\"kss\", k)),\n          lapply(c(0.5, 1, 2), function(k) sens(\"kint\", k))) |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|Parameter |   x| Target (mg)| Residual SD (log)|\n|:---------|---:|-----------:|-----------------:|\n|kkill     | 0.3|       13.48|             0.266|\n|kkill     | 1.0|       15.05|             0.258|\n|kkill     | 3.0|       18.65|             0.252|\n|kss       | 0.3|        6.90|             0.257|\n|kss       | 1.0|       15.05|             0.258|\n|kss       | 3.0|       33.69|             0.284|\n|kint      | 0.5|       27.90|             0.263|\n|kint      | 1.0|       15.05|             0.258|\n|kint      | 2.0|        8.50|             0.253|\n\n\n:::\n:::\n\n\n$K_{ss}$ and $k_{int}$ trade against the target burden almost exactly: a\nthreefold change in either moves the fitted burden by two to three-fold and\nthe residual standard deviation by less than 0.03. That is the\nnon-identifiability stated in Section 1, and it is a property of the algebra\nrather than of this dataset.\n\n$k_{\\rm kill}$ was expected to be different, because it sets how fast the pool\nempties rather than how strongly the drug binds it. **It is not.** A tenfold\nrange moves the residual standard deviation from 0.266 to 0.252, which is no\npreference at all. Three weeks of concentrations through a step-up schedule do\nnot see the emptying rate, and the value of 1 per day used throughout stands\non the biological argument alone. Whether a longer profile constrains it is\nanswerable from the mosunetuzumab panel, which runs to 15 weeks, and has not\nbeen tested.\n\n## 6. What This Does and Does Not Establish\n\n**Established.** A five-state model with no CD3 arm, one shared parameter\nset and one free burden per setting reproduces three published\nconcentration-time datasets spanning three orders of magnitude in dose, and\nthe burdens it wants are ordered the way the diseases are.\n\n**Not established.** That the burdens are correct in absolute terms. They\nare identified only up to the product of pool size, accessibility and\naffinity, so a factor of ten either way is unresolved and only a target\nmeasurement would close it.\n\n**Still open.** Teclistamab, which is subcutaneous and in myeloma rather than\nlymphoma, and whose published paper carries no concentration-time figure, so\nthe profile has to come from the supplement. It is the next setting and the\none most likely to break the structure, because a BCMA target on marrow\nplasma cells is the furthest from the two CD20 settings fitted here.\n",
    "supporting": [
      "class-model_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}