{
  "hash": "8c1b10caa3f78be2902ccb2546588548",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"A Model-Based Comparison for Three Cohorts of Ten\"\nsubtitle: \"Response rates, dose selection and evidence that the population meets the target\"\ndescription: \"Reproducible binomial calculations and simulations comparing observed responder counts with continuous biomarker models, including misspecified dose-response and variance assumptions.\"\ncategories: [Dose-response methods, simulation]\ndate: last-modified\ntoc: true\ntoc-depth: 2\nexecute:\n  echo: false\n  warning: false\n  message: false\n---\n\n\n::: {.cell}\n\n:::\n\n\n**Continuous-data modeling can improve this decision, but the benefit depends\non the assumptions used to share information.** The calculations below keep\nthe response definition fixed: at least an 80% biomarker decline at a\nprespecified assessment, with a target population response rate of 90%.\n\nThese are synthetic, single-assessment examples. They do not quantify the\nadditional benefit of pharmacokinetics (PK) or longitudinal pharmacodynamics\n(PD). The [specification](specification.qmd) defines those comparisons;\nthe [literature review](literature-review.qmd) explains their published basis.\n\n## 1. What Nine Responders Out of Ten Establishes\n\nIf patients independently respond with probability $p$, the probability that\nthe observed cohort passes is\n\n$$\nP(K\\ge9\\mid p)=10p^9(1-p)+p^{10},\\qquad K\\sim\\mathrm{Binomial}(10,p).\n$$\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|True population response rate |Chance of at least 9/10 responders |\n|:-----------------------------|:----------------------------------|\n|50.0%                         |1.1%                               |\n|70.0%                         |14.9%                              |\n|80.0%                         |37.6%                              |\n|85.0%                         |54.4%                              |\n|90.0%                         |73.6%                              |\n|95.0%                         |91.4%                              |\n\n\n:::\n:::\n\n\nA cohort with a true response rate of 80% passes the rule\n37.6% of the time. At exactly the 90% population target,\nthe observed cohort fails 26.4% of the time. These are\nproperties of the rule, before introducing any model.\n\nWhen three independent cohorts all have a true response rate of 80%, at\nleast one passes with probability\n$1-\\{1-P(K\\ge9\\mid p=0.8)\\}^3$ =\n75.7%.\nSelecting any passing dose therefore requires evaluating the whole selection\nprocedure, including the opportunity to pass at several doses.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Observed responders |One-sided 95% exact lower bound on p |Pr(p >= 90% &#124; data), uniform Beta(1,1) prior |\n|:-------------------|:------------------------------------|:-------------------------------------------------|\n|9/10                |60.6%                                |30.3%                                             |\n|10/10               |74.1%                                |68.6%                                             |\n\n\n:::\n:::\n\n\nThe confidence bound and the Bayesian probability answer different questions;\nthe latter depends on the stated prior. Neither analysis of 9/10 establishes\nthe population target with high certainty. Even 10/10 cannot reject\n$H_0:p\\le0.9$ in a conventional, nonrandomized one-sided 5% exact binomial\ntest: its smallest attainable p-value is $0.9^{10}$ = 34.9%.\nWith all successes, at least 29 patients at one\ndose are needed for the one-sided 95% exact lower bound to exceed 90%.\nThis is an all-success bound, not a powered sample size recommendation.\n\n## 2. Estimating the Same Response Rate From Continuous Data\n\nDefine $Y=\\log\\{B(t^*)/B(0)\\}$, where $B$ is a positive biomarker and\n$t^*$ is the assessment time. An 80% decline corresponds to\n$Y\\le c=\\log(0.2)$. Under the illustrative model\n$Y\\mid d\\sim N\\{\\mu(d),\\sigma(d)^2\\}$,\n\n$$\np(d)=\\Phi\\!\\left(\\frac{c-\\mu(d)}{\\sigma(d)}\\right).\n$$\n\nThe fitted mean and the spread both determine the responder fraction.\nEstimating only the mean decline, or counting responders among fitted\nindividual means after shrinkage, does not calculate this population\nquantity. The normal model here describes observed log ratios, so its\nstandard deviation (SD) includes all variation in that observed endpoint.\n\nFor a single dose, the large-sample variance of the plug-in estimate is\napproximately\n\n$$\n\\operatorname{Var}(\\widehat p_{\\rm continuous})\n\\approx\\frac{\\phi(z)^2}{n}\\left(1+\\frac{z^2}{2}\\right),\n\\quad z=\\Phi^{-1}(p).\n$$\n\nThe $z^2/2$ term accounts for estimating the standard deviation. It follows\nby applying the delta method to the sample mean and standard deviation of\nnormal data. The binary estimator has variance $p(1-p)/n$.\nThe ratio of these variances is an approximate ratio of required sample\nsizes for equally precise estimation of $p$.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|True response rate | Binary / continuous variance, SD estimated| Binary / continuous variance, SD known|\n|:------------------|------------------------------------------:|--------------------------------------:|\n|50.0%              |                                       1.57|                                   1.57|\n|80.0%              |                                       1.51|                                   2.04|\n|90.0%              |                                       1.60|                                   2.92|\n|95.0%              |                                       1.90|                                   4.47|\n\n\n:::\n:::\n\n\nAt $p=0.9$, the estimated-SD calculation gives an efficiency factor of\n1.6, equivalent asymptotically\nto a 37.7% sample size reduction\nfor this estimation problem. Treating the SD as known would exaggerate the\ngain when it must be learned from these patients. These calculations are\nneither a finite-sample power result nor an additional benefit from PK.\nThe distributional-estimation idea goes back at least to\n[Suissa (1991)](https://pubmed.ncbi.nlm.nih.gov/1999683/); the calculation\nabove is independently implemented for this example.\n\n## 3. Comparing Dose Decisions\n\nEach simulated study has ten independent patients at each of three relative\ndoses, 1, 2 and 4. There is one observed log biomarker ratio per patient,\ncomplete follow-up, and no assay censoring. All methods receive the same\npatients. The decision is to select the lowest tested dose whose estimated\nresponse probability reaches 90%, or select no dose if none qualifies.\n\n| Method | Information and assumptions |\n|---|---|\n| M0 Counts | Separate responder proportions. A dose passes at 9/10 or 10/10. |\n| M1 Binary monotone | Isotonic binomial estimates: pool neighboring arms only when their observed response rates decrease with dose. |\n| M2 Continuous per arm | Separate normal mean and SD for each dose's log ratio. |\n| M3 Shared SD | Separate means, with a common residual SD estimated from all three arms. |\n| M4 Dose curve | A straight line for mean log ratio against log dose, with a common residual SD. |\n\nM2 isolates the gain from retaining response magnitudes. M3 shares variance\ninformation. M4 also shares information about the means. With equal cohort\nsizes, isotonic least squares on the observed proportions gives the\norder-restricted binomial maximum likelihood estimates used in M1.\nM4's slope is unconstrained; a reversal can be fitted. Its log-dose shape\nonly applies over the tested range and is not a mechanistic dose model.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Scenario                   |Dose 1: p (SD)  |Dose 2: p (SD)  |Dose 4: p (SD)  |\n|:--------------------------|:---------------|:---------------|:---------------|\n|Smooth: middle qualifies   |76.0% (SD 0.45) |92.0% (SD 0.45) |98.2% (SD 0.45) |\n|Smooth: high qualifies     |69.0% (SD 0.45) |84.0% (SD 0.45) |93.2% (SD 0.45) |\n|Plateau: none qualifies    |85.0% (SD 0.45) |85.0% (SD 0.45) |85.0% (SD 0.45) |\n|Late rise: high qualifies  |45.0% (SD 0.45) |65.0% (SD 0.45) |97.0% (SD 0.45) |\n|Unequal SD: none qualifies |75.0% (SD 0.2)  |84.0% (SD 0.4)  |89.0% (SD 0.9)  |\n\n\n:::\n:::\n\n\nThe first two scenarios satisfy M4's shape and common-SD assumptions. The\nplateau also satisfies the linear model, with zero slope. The late-rise\nscenario violates the linear mean shape. The last scenario violates both\nM4's mean shape and the shared-SD assumption; all doses are inadequate.\nM2 remains correctly specified in every scenario because the log ratios\nwithin each arm are normal.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Point-estimate decisions across 10,000 simulated studies per scenario. Correct means the lowest adequate dose, or no dose when all are inadequate. Selecting an inadequate dose means selecting one with true p below 90%. Horizontal bars are Monte Carlo 95% intervals, not uncertainty in the assumed biological scenarios.](worked-comparison_files/figure-html/fig-selection-1.png){#fig-selection width=864}\n:::\n:::\n\n\nWhen only the high dose qualifies under a smooth curve, correct selection\nrises from\n35.9% with\ncounts to\n62.3%\nwith the dose curve. In the late-rise scenario, the shared-SD model with\nseparate means does better than imposing the linear mean shape.\nIn the unequal-SD scenario, variance pooling makes the decision worse.\n\nThe point-estimate rules do not control a 5% false-positive rate. Their\ndifferent false-positive rates also mean that the difference in correct\nselection cannot be called a gain in statistical power at equal type I\nerror. Precision, decision accuracy and evidence against a null hypothesis\nare separate comparisons.\n\n::: {.callout-note collapse=\"true\" title=\"All Point-Estimate Decisions\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Scenario                   |Method                |Correct decision |Inadequate dose |Higher adequate dose |No dose |\n|:--------------------------|:---------------------|:----------------|:---------------|:--------------------|:-------|\n|Smooth: middle qualifies   |M0 Counts             |60.5%            |26.3%           |13.0%                |0.1%    |\n|Smooth: middle qualifies   |M1 Binary monotone    |60.2%            |22.1%           |17.1%                |0.6%    |\n|Smooth: middle qualifies   |M2 Continuous per arm |58.0%            |10.1%           |31.1%                |0.8%    |\n|Smooth: middle qualifies   |M3 Shared SD          |60.4%            |5.7%            |33.4%                |0.6%    |\n|Smooth: middle qualifies   |M4 Dose curve         |67.2%            |4.5%            |27.7%                |0.6%    |\n|Smooth: high qualifies     |M0 Counts             |35.9%            |58.0%           |0.0%                 |6.1%    |\n|Smooth: high qualifies     |M1 Binary monotone    |40.9%            |47.3%           |0.0%                 |11.8%   |\n|Smooth: high qualifies     |M2 Continuous per arm |49.9%            |31.2%           |0.0%                 |19.0%   |\n|Smooth: high qualifies     |M3 Shared SD          |54.4%            |23.4%           |0.0%                 |22.1%   |\n|Smooth: high qualifies     |M4 Dose curve         |62.3%            |13.6%           |0.0%                 |24.1%   |\n|Plateau: none qualifies    |M0 Counts             |9.4%             |90.5%           |0.0%                 |9.4%    |\n|Plateau: none qualifies    |M1 Binary monotone    |37.6%            |62.4%           |0.0%                 |37.6%   |\n|Plateau: none qualifies    |M2 Continuous per arm |31.4%            |68.6%           |0.0%                 |31.4%   |\n|Plateau: none qualifies    |M3 Shared SD          |45.2%            |54.8%           |0.0%                 |45.2%   |\n|Plateau: none qualifies    |M4 Dose curve         |57.6%            |42.4%           |0.0%                 |57.6%   |\n|Late rise: high qualifies  |M0 Counts             |87.8%            |9.1%            |0.0%                 |3.0%    |\n|Late rise: high qualifies  |M1 Binary monotone    |88.2%            |8.4%            |0.0%                 |3.4%    |\n|Late rise: high qualifies  |M2 Continuous per arm |90.5%            |2.5%            |0.0%                 |7.0%    |\n|Late rise: high qualifies  |M3 Shared SD          |94.6%            |0.8%            |0.0%                 |4.6%    |\n|Late rise: high qualifies  |M4 Dose curve         |87.4%            |1.0%            |0.0%                 |11.6%   |\n|Unequal SD: none qualifies |M0 Counts             |11.5%            |88.5%           |0.0%                 |11.5%   |\n|Unequal SD: none qualifies |M1 Binary monotone    |26.1%            |73.9%           |0.0%                 |26.1%   |\n|Unequal SD: none qualifies |M2 Continuous per arm |33.5%            |66.5%           |0.0%                 |33.5%   |\n|Unequal SD: none qualifies |M3 Shared SD          |12.4%            |87.6%           |0.0%                 |12.4%   |\n|Unequal SD: none qualifies |M4 Dose curve         |14.2%            |85.8%           |0.0%                 |14.2%   |\n\n\n:::\n:::\n\n\nWhen all doses are inadequate, a correct decision and a no-dose decision\nare the same event. Those two columns therefore overlap in those scenarios.\nIn scenarios with an adequate dose, the four columns partition the decisions.\n\n:::\n\n## 4. Requiring Evidence That a Dose Exceeds the Target\n\nA second comparison asks for evidence against $H_0:p(d)\\le0.9$.\nEvery method receives a one-sided error allowance of $0.05/3$ per tested\ndose. The Bonferroni bound limits the chance of declaring any truly\ninadequate dose to at most 5%, provided each model's test is valid.\nThe lowest dose that rejects its null is selected.\n\nFor normal data with fitted mean $\\widehat\\mu_d$, residual SD $s$,\nresidual degrees of freedom $\\nu$, and mean-variance factor\n$h_d=\\operatorname{Var}(\\widehat\\mu_d)/\\sigma^2$,\n\n$$\nT_d=\\frac{c-\\widehat\\mu_d}{s\\sqrt{h_d}}\n\\sim t_\\nu\\!\\left(\\frac{z_d}{\\sqrt{h_d}}\\right),\n\\qquad z_d=\\Phi^{-1}\\{p(d)\\}.\n$$\n\nThe noncentral-$t$ distribution gives an exact upper critical value at\n$z_d=\\Phi^{-1}(0.9)$. This accounts for uncertainty in the fitted mean and\nSD. M2 uses $h_d=1/10$, $\\nu=9$; M3 uses $h_d=1/10$, $\\nu=27$; M4 uses\nthe regression prediction variance and $\\nu=28$.\nThe binary comparator uses an exact binomial test. M1 is omitted from this\ncomparison because an order-restricted testing procedure has not been\nimplemented.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Scenario                   |Method                |Correct decision |Inadequate dose |Higher adequate dose |No dose |\n|:--------------------------|:---------------------|:----------------|:---------------|:--------------------|:-------|\n|Smooth: middle qualifies   |M0 Counts             |0.0%             |0.0%            |0.0%                 |100.0%  |\n|Smooth: middle qualifies   |M2 Continuous per arm |2.7%             |0.1%            |19.3%                |77.9%   |\n|Smooth: middle qualifies   |M3 Shared SD          |3.4%             |0.0%            |39.9%                |56.7%   |\n|Smooth: middle qualifies   |M4 Dose curve         |4.6%             |0.0%            |43.5%                |51.9%   |\n|Smooth: high qualifies     |M0 Counts             |0.0%             |0.0%            |0.0%                 |100.0%  |\n|Smooth: high qualifies     |M2 Continuous per arm |3.6%             |0.5%            |0.0%                 |95.9%   |\n|Smooth: high qualifies     |M3 Shared SD          |5.3%             |0.2%            |0.0%                 |94.5%   |\n|Smooth: high qualifies     |M4 Dose curve         |5.6%             |0.1%            |0.0%                 |94.3%   |\n|Plateau: none qualifies    |M0 Counts             |100.0%           |0.0%            |0.0%                 |100.0%  |\n|Plateau: none qualifies    |M2 Continuous per arm |98.4%            |1.6%            |0.0%                 |98.4%   |\n|Plateau: none qualifies    |M3 Shared SD          |99.0%            |1.0%            |0.0%                 |99.0%   |\n|Plateau: none qualifies    |M4 Dose curve         |99.5%            |0.5%            |0.0%                 |99.5%   |\n|Late rise: high qualifies  |M0 Counts             |0.0%             |0.0%            |0.0%                 |100.0%  |\n|Late rise: high qualifies  |M2 Continuous per arm |11.3%            |0.0%            |0.0%                 |88.6%   |\n|Late rise: high qualifies  |M3 Shared SD          |23.5%            |0.0%            |0.0%                 |76.5%   |\n|Late rise: high qualifies  |M4 Dose curve         |11.8%            |0.0%            |0.0%                 |88.2%   |\n|Unequal SD: none qualifies |M0 Counts             |100.0%           |0.0%            |0.0%                 |100.0%  |\n|Unequal SD: none qualifies |M2 Continuous per arm |98.2%            |1.8%            |0.0%                 |98.2%   |\n|Unequal SD: none qualifies |M3 Shared SD          |66.4%            |33.6%           |0.0%                 |66.4%   |\n|Unequal SD: none qualifies |M4 Dose curve         |74.8%            |25.2%           |0.0%                 |74.8%   |\n\n\n:::\n:::\n\n\nThe binary test cannot pass with ten patients per dose, as Section 1 showed.\nThe normal-data tests can pass because they also observe how far the\nresponses lie beyond the threshold. Their power is still limited close to\nthe population target. A more distant, clearly adequate high dose is easier\nto certify than the lowest adequate dose.\n\nThe apparent certainty can fail under misspecification. In the unequal-SD\nscenario, M3 selects an inadequate dose in\n33.6%\nof studies despite its nominal 5% familywise allowance. M2's corresponding\nrate is\n1.8%.\nThis is why an integrated model needs a calibrated decision rule and\nplausible misspecification scenarios before a claim about sample savings.\n\n## 5. Reproduction and Next Comparison\n\nThe [R source](scripts/tdp-calculations.R) contains the settings, generators,\nestimators, decision rules and numerical checks. This page reruns the\ncalculations at render time. The simulation uses\n10,000 replicates per scenario and\nseed 20260922. At that simulation size, the largest possible\nMonte Carlo standard error for a reported proportion is\n0.50 percentage\npoints; uncertainty about the scenario\nparameters is not included.\n\nThe run also returns dose-specific bias and root mean squared error in\n`benchmark$estimates`. The analytical checks verify the binomial tail,\nconfidence-bound calculation, no-dose selection and the noncentral-$t$\ntest's boundary rejection rate by numerical integration.\n\nThe next comparison adds repeated biomarker measurements, followed by PK,\nusing the [same target and decision rules](specification.qmd#integrated-model).\nThose additions must improve on M2–M4 to establish an incremental benefit\nfrom integrated pharmacometric modeling.\n",
    "supporting": [
      "worked-comparison_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}